# Data Wrangling - Feature Engineering

In [70]:
import pandas as pd
import numpy as np

In [71]:
path_file = "Base y archivo de respuestas.xlsx"
hoja = "BASE"
df = pd.read_excel(path_file, sheet_name=hoja)
df.head()

,ID,DIA,INCIDENCIA,MARCA,CANTIDAD,ULTIMA_VENTA_MARCA,PRECIO_1,PRECIO_2,PRECIO_3,PRECIO_4,...,PROMOCION_3,PROMOCION_4,PROMOCION_5,SEXO,ESTADO_CIVIL,EDAD,EDUCACION,INGRESO,OCUPACION,TAMAÑO_CIUDAD
0,200000001,1,0,0,0,0,1.59,1.87,2.01,2.09,...,0,0,0,0,0,47,1,110866,1,0
1,200000001,11,0,0,0,0,1.51,1.89,1.99,2.09,...,0,0,0,0,0,47,1,110866,1,0
2,200000001,12,0,0,0,0,1.51,1.89,1.99,2.09,...,0,0,0,0,0,47,1,110866,1,0
3,200000001,16,0,0,0,0,1.52,1.89,1.98,2.09,...,0,0,0,0,0,47,1,110866,1,0
4,200000001,18,0,0,0,0,1.52,1.89,1.99,2.09,...,0,0,0,0,0,47,1,110866,1,0

In [72]:
df.dtypes

ID                      int64
DIA                     int64
INCIDENCIA              int64
MARCA                   int64
CANTIDAD                int64
ULTIMA_VENTA_MARCA      int64
PRECIO_1              float64
PRECIO_2              float64
PRECIO_3              float64
PRECIO_4              float64
PRECIO_5              float64
PROMOCION_1             int64
PROMOCION_2             int64
PROMOCION_3             int64
PROMOCION_4             int64
PROMOCION_5             int64
SEXO                    int64
ESTADO_CIVIL            int64
EDAD                    int64
EDUCACION               int64
INGRESO                 int64
OCUPACION               int64
TAMAÑO_CIUDAD           int64
dtype: object

In [73]:
df.describe(include = "all")

,ID,DIA,INCIDENCIA,MARCA,CANTIDAD,ULTIMA_VENTA_MARCA,PRECIO_1,PRECIO_2,PRECIO_3,PRECIO_4,...,PROMOCION_3,PROMOCION_4,PROMOCION_5,SEXO,ESTADO_CIVIL,EDAD,EDUCACION,INGRESO,OCUPACION,TAMAÑO_CIUDAD
count,5.869300e+04,58693.000000,58693.000000,58693.000000,58693.000000,58693.000000,58693.000000,58693.000000,58693.000000,58693.000000,...,58693.000000,58693.000000,58693.000000,58693.000000,58693.000000,58693.000000,58693.000000,58693.000000,58693.000000,58693.000000
mean,2.000003e+08,349.431074,0.249399,0.844309,0.691973,0.840799,1.392074,1.780999,2.006789,2.159945,...,0.042799,0.117851,0.035865,0.385889,0.393113,38.793962,1.101579,121841.644319,0.774198,0.655904
std,1.443167e+02,212.045058,0.432669,1.633083,1.498734,1.631628,0.091139,0.170868,0.046867,0.089825,...,0.202405,0.322434,0.185954,0.486809,0.488446,12.052447,0.652499,40643.740678,0.663247,0.794162
min,2.000000e+08,1.000000,0.000000,0.000000,0.000000,0.000000,1.100000,1.260000,1.870000,1.760000,...,0.000000,0.000000,0.000000,0.000000,0.000000,18.000000,0.000000,38247.000000,0.000000,0.000000
25%,2.000001e+08,161.000000,0.000000,0.000000,0.000000,0.000000,1.340000,1.580000,1.970000,2.120000,...,0.000000,0.000000,0.000000,0.000000,0.000000,30.000000,1.000000,95541.000000,0.000000,0.000000
50%,2.000003e+08,343.000000,0.000000,0.000000,0.000000,0.000000,1.390000,1.880000,2.010000,2.170000,...,0.000000,0.000000,0.000000,0.000000,0.000000,36.000000,1.000000,117971.000000,1.000000,0.000000
75%,2.000004e+08,530.000000,0.000000,0.000000,0.000000,0.000000,1.470000,1.890000,2.060000,2.240000,...,0.000000,0.000000,0.000000,1.000000,1.000000,46.000000,1.000000,138525.000000,1.000000,1.000000
max,2.000005e+08,730.000000,1.000000,5.000000,15.000000,5.000000,1.590000,1.900000,2.140000,2.260000,...,1.000000,1.000000,1.000000,1.000000,1.000000,75.000000,3.000000,309364.000000,2.000000,2.000000

Originalmente está pensado hacer el DataFrame de 43 columnas, si hay tiempo, haré el análisis profundo con las otras 36 columnas:

In [74]:
headers_df_final = ["Sexo", "Estado Civil", "Edad", "Educacion", "Ingreso", "Ocupacion", "Tamaño Ciudad", "Cantidad Visitas", "Recencia", "Frecuencia", "Valor Monetario", "Cantidad Marca 1", "Cantidad Marca 2", "Cantidad Marca 3", "Cantidad Marca 4", "Cantidad Marca 5", "Cantidad Comprada", "% Dias de Compra", "Compras Seguidas", "Compras Promocion 1", "Compras Promocion 2", "Compras Promocion 3", "Compras Promocion 4", "Compras Promocion 5", "Total Compras Promocion", "Total Prom 1", "Total Prom 2", "Total Prom 3", "Total Prom 4", "Total Prom 5", "Total Proms", "% Prom 1", "% Prom 2", "% Prom 3", "% Prom 4", "% Prom 5", "% Proms", "% Prom 1 Compra", "% Prom 2 Compra", "% Prom 3 Compra", "% Prom 4 Compra", "% Prom 5 Compra", "% Prom Compra"] 
headers_df_final_deep = ["Prom 1 Previa", "Prom 2 Previa", "Prom 3 Previa", "Prom 4 Previa", "Prom 5 Previa", "Total Prom Previa", "No Prom 1 Previa", "No Prom 2 Previa", "No Prom 3 Previa", "No Prom 4 Previa", "No Prom 5 Previa", "Total No Prom Previa", "Prod 1 Baja Precio", "Prod 2 Baja Precio", "Prod 3 Baja Precio", "Prod 4 Baja Precio", "Prod 5 Baja Precio", "Prod Total Baja Precio", "Prod 1 Sube Precio", "Prod 2 Sube Precio", "Prod 3 Sube Precio", "Prod 4 Sube Precio", "Prod 5 Sube Precio", "Prod Total Sube Precio", "Prod 1 Igual Precio", "Prod 2 Igual Precio", "Prod 3 Igual Precio", "Prod 4 Igual Precio", "Prod 5 Igual Precio", "Prod Total Igual Precio", "Prom 1 Variacion Precio", "Prom 2 Variacion Precio", "Prom 3 Variacion Precio", "Prom 4 Variacion Precio", "Prom 5 Variacion Precio", "Prom Variacion Precio"]

In [75]:
len(headers_df_final)

43

In [76]:
len(headers_df_final_deep)

36

En total hay 500 clientes que van a analizarse, así que el DataFrame final tendrá un total de 500 filas:

In [77]:
len(df['ID'].unique())

500

In [78]:
header_Id_Cantidad = ['Cantidad de Visitas']
Id_Cantidad = df['ID'].value_counts()
Id_Cantidad = pd.DataFrame(Id_Cantidad)
Id_Cantidad = Id_Cantidad.sort_index()
Id_Cantidad.columns = header_Id_Cantidad 
Id_Cantidad.reset_index(drop=True, inplace=True)
Id_Cantidad.head()

   Cantidad de Visitas
0                  101
1                   87
2                   97
3                   85
4                  111

In [79]:
df_final = df.groupby(['ID'],as_index=False).mean()
df_final.head()

,ID,DIA,INCIDENCIA,MARCA,CANTIDAD,ULTIMA_VENTA_MARCA,PRECIO_1,PRECIO_2,PRECIO_3,PRECIO_4,...,PROMOCION_3,PROMOCION_4,PROMOCION_5,SEXO,ESTADO_CIVIL,EDAD,EDUCACION,INGRESO,OCUPACION,TAMAÑO_CIUDAD
0,200000001,333.207921,0.089109,0.267327,0.178218,0.267327,1.395149,1.779208,2.008119,2.151188,...,0.059406,0.148515,0.049505,0.0,0.0,47.0,1.0,110866.0,1.0,0.0
1,200000002,350.931034,0.126437,0.482759,0.229885,0.482759,1.393678,1.788506,2.007011,2.156437,...,0.022989,0.160920,0.034483,1.0,1.0,52.0,2.0,159052.0,2.0,1.0
2,200000003,358.536082,0.103093,0.268041,0.185567,0.268041,1.398763,1.758144,2.005670,2.165464,...,0.020619,0.123711,0.020619,0.0,0.0,28.0,0.0,113212.0,1.0,0.0
3,200000004,369.941176,0.129412,0.611765,0.152941,0.552941,1.401059,1.787176,2.011765,2.155882,...,0.035294,0.141176,0.035294,0.0,0.0,37.0,1.0,119602.0,0.0,0.0
4,200000005,362.558559,0.117117,0.585586,0.189189,0.585586,1.392342,1.791622,2.005856,2.162883,...,0.018018,0.117117,0.018018,0.0,0.0,49.0,1.0,121466.0,1.0,2.0

In [80]:
df_final = df_final[['ID', 'SEXO', 'ESTADO_CIVIL', 'EDAD', 'EDUCACION', 'INGRESO', 'OCUPACION', 'TAMAÑO_CIUDAD']]
df_final.head()

,ID,SEXO,ESTADO_CIVIL,EDAD,EDUCACION,INGRESO,OCUPACION,TAMAÑO_CIUDAD
0,200000001,0.0,0.0,47.0,1.0,110866.0,1.0,0.0
1,200000002,1.0,1.0,52.0,2.0,159052.0,2.0,1.0
2,200000003,0.0,0.0,28.0,0.0,113212.0,1.0,0.0
3,200000004,0.0,0.0,37.0,1.0,119602.0,0.0,0.0
4,200000005,0.0,0.0,49.0,1.0,121466.0,1.0,2.0

In [81]:
header_Id_Cantidad = ['Cantidad de Visitas']
Id_Cantidad = df['ID'].value_counts()
Id_Cantidad = pd.DataFrame(Id_Cantidad)
Id_Cantidad = Id_Cantidad.sort_index()
Id_Cantidad.columns = header_Id_Cantidad 
Id_Cantidad.reset_index(drop=True, inplace=True)
Id_Cantidad.head()
df_final = pd.concat([df_final, Id_Cantidad], axis=1)
#df_final[['Cantidad de Visitas']] = Id_Cantidad[['ID']]
df_final

,ID,SEXO,ESTADO_CIVIL,EDAD,EDUCACION,INGRESO,OCUPACION,TAMAÑO_CIUDAD,Cantidad de Visitas
0,200000001,0.0,0.0,47.0,1.0,110866.0,1.0,0.0,101
1,200000002,1.0,1.0,52.0,2.0,159052.0,2.0,1.0,87
2,200000003,0.0,0.0,28.0,0.0,113212.0,1.0,0.0,97
3,200000004,0.0,0.0,37.0,1.0,119602.0,0.0,0.0,85
4,200000005,0.0,0.0,49.0,1.0,121466.0,1.0,2.0,111
...,...,...,...,...,...,...,...,...,...
495,200000496,1.0,1.0,26.0,1.0,71021.0,0.0,0.0,120
496,200000497,0.0,0.0,60.0,2.0,89374.0,0.0,0.0,120
497,200000498,1.0,1.0,29.0,1.0,114784.0,1.0,0.0,131
498,200000499,1.0,0.0,35.0,1.0,73266.0,0.0,0.0,106
499,200000500,0.0,0.0,42.0,1.0,120946.0,1.0,0.0,124

In [82]:
df_Indice_Dias = df[['ID','DIA']]
df_Indice_Dias = df_Indice_Dias.groupby(["ID"],as_index=False).max()
df_Indice_Dias = df_Indice_Dias.drop(['ID'], axis=1)
header_df_Indice_Dias = ['Ultimo Dia Visita']
df_Indice_Dias.columns = header_df_Indice_Dias
df_final = pd.concat([df_final, df_Indice_Dias], axis=1)
df_final

,ID,SEXO,ESTADO_CIVIL,EDAD,EDUCACION,INGRESO,OCUPACION,TAMAÑO_CIUDAD,Cantidad de Visitas,Ultimo Dia Visita
0,200000001,0.0,0.0,47.0,1.0,110866.0,1.0,0.0,101,727
1,200000002,1.0,1.0,52.0,2.0,159052.0,2.0,1.0,87,729
2,200000003,0.0,0.0,28.0,0.0,113212.0,1.0,0.0,97,724
3,200000004,0.0,0.0,37.0,1.0,119602.0,0.0,0.0,85,725
4,200000005,0.0,0.0,49.0,1.0,121466.0,1.0,2.0,111,729
...,...,...,...,...,...,...,...,...,...,...
495,200000496,1.0,1.0,26.0,1.0,71021.0,0.0,0.0,120,723
496,200000497,0.0,0.0,60.0,2.0,89374.0,0.0,0.0,120,722
497,200000498,1.0,1.0,29.0,1.0,114784.0,1.0,0.0,131,729
498,200000499,1.0,0.0,35.0,1.0,73266.0,0.0,0.0,106,727
499,200000500,0.0,0.0,42.0,1.0,120946.0,1.0,0.0,124,726

In [83]:
df_final['Dias sin Visita'] = 731 - df_final['Ultimo Dia Visita']
df_final = df_final.drop(['Ultimo Dia Visita'], axis=1)
df_final.head()

,ID,SEXO,ESTADO_CIVIL,EDAD,EDUCACION,INGRESO,OCUPACION,TAMAÑO_CIUDAD,Cantidad de Visitas,Dias sin Visita
0,200000001,0.0,0.0,47.0,1.0,110866.0,1.0,0.0,101,4
1,200000002,1.0,1.0,52.0,2.0,159052.0,2.0,1.0,87,2
2,200000003,0.0,0.0,28.0,0.0,113212.0,1.0,0.0,97,7
3,200000004,0.0,0.0,37.0,1.0,119602.0,0.0,0.0,85,6
4,200000005,0.0,0.0,49.0,1.0,121466.0,1.0,2.0,111,2

In [84]:
lista_dias_de_compra = np.empty(len(df))

for i in range(len(df)): 
    if df.loc[i, 'INCIDENCIA'] == 0:
        lista_dias_de_compra[i] = 0
    else:
        lista_dias_de_compra[i] = df.loc[i, 'DIA']

df_lista_dias_de_compra = pd.DataFrame(lista_dias_de_compra) 
header_df_lista_dias_de_compra = ['Dia Final de Compra']
df_lista_dias_de_compra.columns = header_df_lista_dias_de_compra
df_dias_compra = df[['ID']]
df_dias_compra = pd.concat([df_dias_compra, df_lista_dias_de_compra], axis=1)
df_dias_compra = df_dias_compra.groupby(["ID"],as_index=False).max()
df_dias_compra = df_dias_compra.drop(['ID'], axis=1)
df_final = pd.concat([df_final, df_dias_compra], axis=1)
df_final['Recencia'] = 731 - df_final['Dia Final de Compra']
df_final.head()

,ID,SEXO,ESTADO_CIVIL,EDAD,EDUCACION,INGRESO,OCUPACION,TAMAÑO_CIUDAD,Cantidad de Visitas,Dias sin Visita,Dia Final de Compra,Recencia
0,200000001,0.0,0.0,47.0,1.0,110866.0,1.0,0.0,101,4,702.0,29.0
1,200000002,1.0,1.0,52.0,2.0,159052.0,2.0,1.0,87,2,538.0,193.0
2,200000003,0.0,0.0,28.0,0.0,113212.0,1.0,0.0,97,7,721.0,10.0
3,200000004,0.0,0.0,37.0,1.0,119602.0,0.0,0.0,85,6,725.0,6.0
4,200000005,0.0,0.0,49.0,1.0,121466.0,1.0,2.0,111,2,640.0,91.0

In [85]:
df_Indice_Incidencia = df[['ID','INCIDENCIA']]
df_cantidad_ventas_efectivas = df_Indice_Incidencia.groupby(["ID"],as_index=False).sum()

df_cantidad_ventas_efectivas = df_cantidad_ventas_efectivas.drop(['ID'], axis=1)
header_df_cantidad_ventas_efectivas = ['Cantidad Ventas Efectivas']
df_cantidad_ventas_efectivas.columns = header_df_cantidad_ventas_efectivas
df_final = pd.concat([df_final, df_cantidad_ventas_efectivas], axis=1)
df_final

,ID,SEXO,ESTADO_CIVIL,EDAD,EDUCACION,INGRESO,OCUPACION,TAMAÑO_CIUDAD,Cantidad de Visitas,Dias sin Visita,Dia Final de Compra,Recencia,Cantidad Ventas Efectivas
0,200000001,0.0,0.0,47.0,1.0,110866.0,1.0,0.0,101,4,702.0,29.0,9
1,200000002,1.0,1.0,52.0,2.0,159052.0,2.0,1.0,87,2,538.0,193.0,11
2,200000003,0.0,0.0,28.0,0.0,113212.0,1.0,0.0,97,7,721.0,10.0,10
3,200000004,0.0,0.0,37.0,1.0,119602.0,0.0,0.0,85,6,725.0,6.0,11
4,200000005,0.0,0.0,49.0,1.0,121466.0,1.0,2.0,111,2,640.0,91.0,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,200000496,1.0,1.0,26.0,1.0,71021.0,0.0,0.0,120,8,624.0,107.0,20
496,200000497,0.0,0.0,60.0,2.0,89374.0,0.0,0.0,120,9,713.0,18.0,43
497,200000498,1.0,1.0,29.0,1.0,114784.0,1.0,0.0,131,2,725.0,6.0,39
498,200000499,1.0,0.0,35.0,1.0,73266.0,0.0,0.0,106,4,727.0,4.0,31
499,200000500,0.0,0.0,42.0,1.0,120946.0,1.0,0.0,124,5,722.0,9.0,15

In [86]:
df_final['Frecuencia_ventas_por_visita'] = df_final['Cantidad Ventas Efectivas']/df_final['Cantidad de Visitas']
df_final['Frecuencia_ventas_por_dia'] = df_final['Cantidad Ventas Efectivas'] / 731

In [87]:
df_valor_monetario = df[['ID', 'MARCA', 'CANTIDAD', 'PRECIO_1', 'PRECIO_2', 'PRECIO_3', 'PRECIO_4', 'PRECIO_5']]
df_valor_monetario.head()

#df_valor_monetario['Valor Monetario'] =  df_valor_monetario['CANTIDAD']*df_valor_monetario['PRECIO_']

,ID,MARCA,CANTIDAD,PRECIO_1,PRECIO_2,PRECIO_3,PRECIO_4,PRECIO_5
0,200000001,0,0,1.59,1.87,2.01,2.09,2.66
1,200000001,0,0,1.51,1.89,1.99,2.09,2.66
2,200000001,0,0,1.51,1.89,1.99,2.09,2.66
3,200000001,0,0,1.52,1.89,1.98,2.09,2.66
4,200000001,0,0,1.52,1.89,1.99,2.09,2.66

In [88]:
len(df_valor_monetario)

58693

In [89]:
lista_valor_monetario = np.empty(len(df))

for i in range(len(df_valor_monetario)): 
    if df_valor_monetario.loc[i, 'MARCA'] == 0:
        lista_valor_monetario[i] = 0
    elif df_valor_monetario.loc[i, 'MARCA'] == 1:
        lista_valor_monetario[i] = df_valor_monetario.loc[i, 'CANTIDAD']*df_valor_monetario.loc[i, 'PRECIO_1']
    elif df_valor_monetario.loc[i, 'MARCA'] == 2:
        lista_valor_monetario[i] = df_valor_monetario.loc[i, 'CANTIDAD']*df_valor_monetario.loc[i, 'PRECIO_2']
    elif df_valor_monetario.loc[i, 'MARCA'] == 3:
        lista_valor_monetario[i] = df_valor_monetario.loc[i, 'CANTIDAD']*df_valor_monetario.loc[i, 'PRECIO_3']
    elif df_valor_monetario.loc[i, 'MARCA'] == 4:
        lista_valor_monetario[i] = df_valor_monetario.loc[i, 'CANTIDAD']*df_valor_monetario.loc[i, 'PRECIO_4']
    else:
        lista_valor_monetario[i] = df_valor_monetario.loc[i, 'CANTIDAD']*df_valor_monetario.loc[i, 'PRECIO_5']
    

df_lista_valor_monetario = pd.DataFrame(lista_valor_monetario)
df_lista_valor_monetario

header_df_lista_valor_monetario = ['Valor Monetario']
df_lista_valor_monetario.columns = header_df_lista_valor_monetario
df = pd.concat([df, df_lista_valor_monetario], axis=1)

In [90]:
df_lista_valor_monetario = df[['ID', 'Valor Monetario']]
df_lista_valor_monetario = df_lista_valor_monetario.groupby(['ID'],as_index=False).sum()
df_lista_valor_monetario = df_lista_valor_monetario.drop(['ID'], axis=1)
df_final = pd.concat([df_final, df_lista_valor_monetario], axis=1)
df_final.head(10)

,ID,SEXO,ESTADO_CIVIL,EDAD,EDUCACION,INGRESO,OCUPACION,TAMAÑO_CIUDAD,Cantidad de Visitas,Dias sin Visita,Dia Final de Compra,Recencia,Cantidad Ventas Efectivas,Frecuencia_ventas_por_visita,Frecuencia_ventas_por_dia,Valor Monetario
0,200000001,0.0,0.0,47.0,1.0,110866.0,1.0,0.0,101,4,702.0,29.0,9,0.089109,0.012312,33.96
1,200000002,1.0,1.0,52.0,2.0,159052.0,2.0,1.0,87,2,538.0,193.0,11,0.126437,0.015048,41.74
2,200000003,0.0,0.0,28.0,0.0,113212.0,1.0,0.0,97,7,721.0,10.0,10,0.103093,0.013680,32.27
3,200000004,0.0,0.0,37.0,1.0,119602.0,0.0,0.0,85,6,725.0,6.0,11,0.129412,0.015048,32.96
4,200000005,0.0,0.0,49.0,1.0,121466.0,1.0,2.0,111,2,640.0,91.0,13,0.117117,0.017784,54.97
5,200000006,0.0,0.0,39.0,1.0,112347.0,1.0,2.0,86,4,636.0,95.0,10,0.116279,0.013680,40.86
6,200000007,0.0,0.0,27.0,0.0,125190.0,2.0,1.0,83,10,634.0,97.0,16,0.192771,0.021888,55.34
7,200000008,0.0,0.0,26.0,0.0,131122.0,1.0,0.0,97,2,721.0,10.0,15,0.154639,0.020520,61.04
8,200000009,0.0,0.0,25.0,0.0,108960.0,0.0,0.0,102,8,671.0,60.0,9,0.088235,0.012312,17.75
9,200000010,0.0,0.0,32.0,0.0,69370.0,0.0,0.0,98,1,682.0,49.0,15,0.153061,0.020520,78.80

In [91]:
df_respuesta2a = df_final[['ID', 'Recencia', 'Cantidad Ventas Efectivas', 'Valor Monetario']]
#df_respuesta2a.to_excel("Respuesta2a.xlsx", index=False)

In [92]:
lista_marca_1 = np.empty(len(df))
lista_marca_2 = np.empty(len(df))
lista_marca_3 = np.empty(len(df))
lista_marca_4 = np.empty(len(df))
lista_marca_5 = np.empty(len(df))
valor_monetario_marca_1 = np.empty(len(df))
valor_monetario_marca_2 = np.empty(len(df))
valor_monetario_marca_3 = np.empty(len(df))
valor_monetario_marca_4 = np.empty(len(df))
valor_monetario_marca_5 = np.empty(len(df))

for i in range(len(df)): 
    if df.loc[i, 'MARCA'] == 0:
        lista_marca_1[i] = 0
        lista_marca_2[i] = 0
        lista_marca_3[i] = 0
        lista_marca_4[i] = 0
        lista_marca_5[i] = 0
        valor_monetario_marca_1[i] = 0
        valor_monetario_marca_2[i] = 0
        valor_monetario_marca_3[i] = 0
        valor_monetario_marca_4[i] = 0
        valor_monetario_marca_5[i] = 0
    elif df_valor_monetario.loc[i, 'MARCA'] == 1:
        lista_marca_1[i] = df.loc[i, 'CANTIDAD']
        lista_marca_2[i] = 0
        lista_marca_3[i] = 0
        lista_marca_4[i] = 0
        lista_marca_5[i] = 0
        valor_monetario_marca_1[i] = df.loc[i, 'CANTIDAD']*df_valor_monetario.loc[i, 'PRECIO_1']
        valor_monetario_marca_2[i] = 0
        valor_monetario_marca_3[i] = 0
        valor_monetario_marca_4[i] = 0
        valor_monetario_marca_5[i] = 0
    elif df_valor_monetario.loc[i, 'MARCA'] == 2:
        lista_marca_1[i] = 0
        lista_marca_2[i] = df.loc[i, 'CANTIDAD']
        lista_marca_3[i] = 0
        lista_marca_4[i] = 0
        lista_marca_5[i] = 0
        valor_monetario_marca_1[i] = 0
        valor_monetario_marca_2[i] = df.loc[i, 'CANTIDAD']*df_valor_monetario.loc[i, 'PRECIO_2']
        valor_monetario_marca_3[i] = 0
        valor_monetario_marca_4[i] = 0
        valor_monetario_marca_5[i] = 0
    elif df_valor_monetario.loc[i, 'MARCA'] == 3:
        lista_marca_1[i] = 0
        lista_marca_2[i] = 0
        lista_marca_3[i] = df.loc[i, 'CANTIDAD']
        lista_marca_4[i] = 0
        lista_marca_5[i] = 0
        valor_monetario_marca_1[i] = 0
        valor_monetario_marca_2[i] = 0
        valor_monetario_marca_3[i] = df.loc[i, 'CANTIDAD']*df_valor_monetario.loc[i, 'PRECIO_3']
        valor_monetario_marca_4[i] = 0
        valor_monetario_marca_5[i] = 0
    elif df_valor_monetario.loc[i, 'MARCA'] == 4:
        lista_marca_1[i] = 0
        lista_marca_2[i] = 0
        lista_marca_3[i] = 0
        lista_marca_4[i] = df.loc[i, 'CANTIDAD']
        lista_marca_5[i] = 0
        valor_monetario_marca_1[i] = 0
        valor_monetario_marca_2[i] = 0
        valor_monetario_marca_3[i] = 0
        valor_monetario_marca_4[i] = df.loc[i, 'CANTIDAD']*df_valor_monetario.loc[i, 'PRECIO_4']
        valor_monetario_marca_5[i] = 0
    else:
        lista_marca_1[i] = 0
        lista_marca_2[i] = 0
        lista_marca_3[i] = 0
        lista_marca_4[i] = 0
        lista_marca_5[i] = df.loc[i, 'CANTIDAD']
        valor_monetario_marca_1[i] = 0
        valor_monetario_marca_2[i] = 0
        valor_monetario_marca_3[i] = 0
        valor_monetario_marca_4[i] = 0
        valor_monetario_marca_5[i] = df.loc[i, 'CANTIDAD']*df_valor_monetario.loc[i, 'PRECIO_5']
    

    
lista_marca_1 = pd.DataFrame(lista_marca_1)
lista_marca_2 = pd.DataFrame(lista_marca_2)
lista_marca_3 = pd.DataFrame(lista_marca_3)
lista_marca_4 = pd.DataFrame(lista_marca_4)
lista_marca_5 = pd.DataFrame(lista_marca_5)
valor_monetario_marca_1 = pd.DataFrame(valor_monetario_marca_1)
valor_monetario_marca_2 = pd.DataFrame(valor_monetario_marca_2)
valor_monetario_marca_3 = pd.DataFrame(valor_monetario_marca_3)
valor_monetario_marca_4 = pd.DataFrame(valor_monetario_marca_4)
valor_monetario_marca_5 = pd.DataFrame(valor_monetario_marca_5)

header_df_lista_marca_1 = ['Cantidad Marca 1']
header_df_lista_marca_2 = ['Cantidad Marca 2']
header_df_lista_marca_3 = ['Cantidad Marca 3']
header_df_lista_marca_4 = ['Cantidad Marca 4']
header_df_lista_marca_5 = ['Cantidad Marca 5']
header_valor_monetario_marca_1 = ['Valor Monetario Marca 1']
header_valor_monetario_marca_2 = ['Valor Monetario Marca 2']
header_valor_monetario_marca_3 = ['Valor Monetario Marca 3']
header_valor_monetario_marca_4 = ['Valor Monetario Marca 4']
header_valor_monetario_marca_5 = ['Valor Monetario Marca 5']

lista_marca_1.columns = header_df_lista_marca_1
lista_marca_2.columns = header_df_lista_marca_2
lista_marca_3.columns = header_df_lista_marca_3
lista_marca_4.columns = header_df_lista_marca_4
lista_marca_5.columns = header_df_lista_marca_5
valor_monetario_marca_1.columns = header_valor_monetario_marca_1
valor_monetario_marca_2.columns = header_valor_monetario_marca_2
valor_monetario_marca_3.columns = header_valor_monetario_marca_3
valor_monetario_marca_4.columns = header_valor_monetario_marca_4
valor_monetario_marca_5.columns = header_valor_monetario_marca_5

#lista_marca_4.head(50)
df = pd.concat([df, lista_marca_1, lista_marca_2, lista_marca_3, lista_marca_4, lista_marca_5, valor_monetario_marca_1, valor_monetario_marca_2, valor_monetario_marca_3, valor_monetario_marca_4, valor_monetario_marca_5], axis=1)
df.head(20)

,ID,DIA,INCIDENCIA,MARCA,CANTIDAD,ULTIMA_VENTA_MARCA,PRECIO_1,PRECIO_2,PRECIO_3,PRECIO_4,...,Cantidad Marca 1,Cantidad Marca 2,Cantidad Marca 3,Cantidad Marca 4,Cantidad Marca 5,Valor Monetario Marca 1,Valor Monetario Marca 2,Valor Monetario Marca 3,Valor Monetario Marca 4,Valor Monetario Marca 5
0,200000001,1,0,0,0,0,1.59,1.87,2.01,2.09,...,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00
1,200000001,11,0,0,0,0,1.51,1.89,1.99,2.09,...,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00
2,200000001,12,0,0,0,0,1.51,1.89,1.99,2.09,...,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00
3,200000001,16,0,0,0,0,1.52,1.89,1.98,2.09,...,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00
4,200000001,18,0,0,0,0,1.52,1.89,1.99,2.09,...,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00
5,200000001,23,0,0,0,0,1.50,1.90,1.99,2.09,...,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00
6,200000001,28,1,2,2,0,1.50,1.90,1.99,2.09,...,0.0,2.0,0.0,0.0,0.0,0.00,3.8,0.0,0.0,0.00
7,200000001,37,0,0,0,2,1.50,1.90,1.99,2.09,...,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00
8,200000001,41,0,0,0,0,1.35,1.58,1.97,2.09,...,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00
9,200000001,43,0,0,0,0,1.35,1.58,1.97,2.09,...,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00
10,200000001,51,0,0,0,0,1.35,1.87,1.93,2.09,...,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00
11,200000001,58,1,5,1,0,1.39,1.90,1.91,2.12,...,0.0,0.0,0.0,0.0,1.0,0.00,0.0,0.0,0.0,2.62
12,200000001,59,0,0,0,5,1.39,1.90,1.91,2.12,...,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00
13,200000001,77,0,0,0,0,1.36,1.85,1.95,2.12,...,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00
14,200000001,78,0,0,0,0,1.47,1.85,1.95,2.12,...,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00
15,200000001,83,0,0,0,0,1.47,1.90,1.99,2.12,...,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00
16,200000001,90,0,0,0,0,1.39,1.58,1.99,2.12,...,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00
17,200000001,92,0,0,0,0,1.39,1.46,1.99,2.12,...,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00
18,200000001,98,0,0,0,0,1.47,1.90,1.95,2.12,...,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00
19,200000001,110,1,1,2,0,1.47,1.90,1.99,1.97,...,2.0,0.0,0.0,0.0,0.0,2.94,0.0,0.0,0.0,0.00

In [93]:
df_por_marca = df[['ID', 'Cantidad Marca 1', 'Cantidad Marca 2', 'Cantidad Marca 3', 'Cantidad Marca 4', 'Cantidad Marca 5', 'Valor Monetario Marca 1', 'Valor Monetario Marca 2', 'Valor Monetario Marca 3', 'Valor Monetario Marca 4', 'Valor Monetario Marca 5']]
df_por_marca = df_por_marca.groupby(['ID'],as_index=False).sum()
df_por_marca = df_por_marca.drop(['ID'], axis=1)
df_final = pd.concat([df_final, df_por_marca], axis=1)
df_final.head(10)

,ID,SEXO,ESTADO_CIVIL,EDAD,EDUCACION,INGRESO,OCUPACION,TAMAÑO_CIUDAD,Cantidad de Visitas,Dias sin Visita,...,Cantidad Marca 1,Cantidad Marca 2,Cantidad Marca 3,Cantidad Marca 4,Cantidad Marca 5,Valor Monetario Marca 1,Valor Monetario Marca 2,Valor Monetario Marca 3,Valor Monetario Marca 4,Valor Monetario Marca 5
0,200000001,0.0,0.0,47.0,1.0,110866.0,1.0,0.0,101,4,...,2.0,10.0,0.0,4.0,2.0,2.94,17.75,0.00,7.86,5.41
1,200000002,1.0,1.0,52.0,2.0,159052.0,2.0,1.0,87,2,...,0.0,3.0,0.0,17.0,0.0,0.00,4.71,0.00,37.03,0.00
2,200000003,0.0,0.0,28.0,0.0,113212.0,1.0,0.0,97,7,...,0.0,16.0,0.0,0.0,2.0,0.00,27.34,0.00,0.00,4.93
3,200000004,0.0,0.0,37.0,1.0,119602.0,0.0,0.0,85,6,...,0.0,1.0,0.0,0.0,12.0,0.00,1.57,0.00,0.00,31.39
4,200000005,0.0,0.0,49.0,1.0,121466.0,1.0,2.0,111,2,...,0.0,0.0,0.0,0.0,21.0,0.00,0.00,0.00,0.00,54.97
5,200000006,0.0,0.0,39.0,1.0,112347.0,1.0,2.0,86,4,...,5.0,2.0,0.0,0.0,12.0,6.55,3.14,0.00,0.00,31.17
6,200000007,0.0,0.0,27.0,0.0,125190.0,2.0,1.0,83,10,...,1.0,16.0,5.0,3.0,4.0,1.35,26.40,10.13,6.78,10.68
7,200000008,0.0,0.0,26.0,0.0,131122.0,1.0,0.0,97,2,...,0.0,27.0,0.0,0.0,6.0,0.00,45.36,0.00,0.00,15.68
8,200000009,0.0,0.0,25.0,0.0,108960.0,0.0,0.0,102,8,...,2.0,9.0,0.0,0.0,0.0,2.42,15.33,0.00,0.00,0.00
9,200000010,0.0,0.0,32.0,0.0,69370.0,0.0,0.0,98,1,...,12.0,35.0,0.0,0.0,0.0,16.42,62.38,0.00,0.00,0.00

In [94]:
df_final['Total Comprados'] = df_final['Cantidad Marca 1'] + df_final['Cantidad Marca 2'] + df_final['Cantidad Marca 3'] + df_final['Cantidad Marca 4'] + df_final['Cantidad Marca 5']
df_final

,ID,SEXO,ESTADO_CIVIL,EDAD,EDUCACION,INGRESO,OCUPACION,TAMAÑO_CIUDAD,Cantidad de Visitas,Dias sin Visita,...,Cantidad Marca 2,Cantidad Marca 3,Cantidad Marca 4,Cantidad Marca 5,Valor Monetario Marca 1,Valor Monetario Marca 2,Valor Monetario Marca 3,Valor Monetario Marca 4,Valor Monetario Marca 5,Total Comprados
0,200000001,0.0,0.0,47.0,1.0,110866.0,1.0,0.0,101,4,...,10.0,0.0,4.0,2.0,2.94,17.75,0.00,7.86,5.41,18.0
1,200000002,1.0,1.0,52.0,2.0,159052.0,2.0,1.0,87,2,...,3.0,0.0,17.0,0.0,0.00,4.71,0.00,37.03,0.00,20.0
2,200000003,0.0,0.0,28.0,0.0,113212.0,1.0,0.0,97,7,...,16.0,0.0,0.0,2.0,0.00,27.34,0.00,0.00,4.93,18.0
3,200000004,0.0,0.0,37.0,1.0,119602.0,0.0,0.0,85,6,...,1.0,0.0,0.0,12.0,0.00,1.57,0.00,0.00,31.39,13.0
4,200000005,0.0,0.0,49.0,1.0,121466.0,1.0,2.0,111,2,...,0.0,0.0,0.0,21.0,0.00,0.00,0.00,0.00,54.97,21.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,200000496,1.0,1.0,26.0,1.0,71021.0,0.0,0.0,120,8,...,37.0,0.0,2.0,8.0,2.98,62.47,0.00,3.78,21.30,49.0
496,200000497,0.0,0.0,60.0,2.0,89374.0,0.0,0.0,120,9,...,176.0,0.0,67.0,1.0,4.76,305.55,0.00,147.30,2.70,248.0
497,200000498,1.0,1.0,29.0,1.0,114784.0,1.0,0.0,131,2,...,77.0,33.0,0.0,0.0,18.48,133.55,67.62,0.00,0.00,125.0
498,200000499,1.0,0.0,35.0,1.0,73266.0,0.0,0.0,106,4,...,79.0,0.0,3.0,6.0,8.01,127.25,0.00,6.72,15.87,94.0
499,200000500,0.0,0.0,42.0,1.0,120946.0,1.0,0.0,124,5,...,76.0,0.0,0.0,0.0,24.42,126.62,0.00,0.00,0.00,94.0

In [95]:
df_final['% Visitas Efectivas'] = (df_final['Cantidad Ventas Efectivas']*100)/df_final['Cantidad de Visitas']
df_final['Frecuencia de Visitas'] = df_final['Cantidad de Visitas']/731
df_final.head(20)

,ID,SEXO,ESTADO_CIVIL,EDAD,EDUCACION,INGRESO,OCUPACION,TAMAÑO_CIUDAD,Cantidad de Visitas,Dias sin Visita,...,Cantidad Marca 4,Cantidad Marca 5,Valor Monetario Marca 1,Valor Monetario Marca 2,Valor Monetario Marca 3,Valor Monetario Marca 4,Valor Monetario Marca 5,Total Comprados,% Visitas Efectivas,Frecuencia de Visitas
0,200000001,0.0,0.0,47.0,1.0,110866.0,1.0,0.0,101,4,...,4.0,2.0,2.94,17.75,0.00,7.86,5.41,18.0,8.910891,0.138167
1,200000002,1.0,1.0,52.0,2.0,159052.0,2.0,1.0,87,2,...,17.0,0.0,0.00,4.71,0.00,37.03,0.00,20.0,12.643678,0.119015
2,200000003,0.0,0.0,28.0,0.0,113212.0,1.0,0.0,97,7,...,0.0,2.0,0.00,27.34,0.00,0.00,4.93,18.0,10.309278,0.132695
3,200000004,0.0,0.0,37.0,1.0,119602.0,0.0,0.0,85,6,...,0.0,12.0,0.00,1.57,0.00,0.00,31.39,13.0,12.941176,0.116279
4,200000005,0.0,0.0,49.0,1.0,121466.0,1.0,2.0,111,2,...,0.0,21.0,0.00,0.00,0.00,0.00,54.97,21.0,11.711712,0.151847
5,200000006,0.0,0.0,39.0,1.0,112347.0,1.0,2.0,86,4,...,0.0,12.0,6.55,3.14,0.00,0.00,31.17,19.0,11.627907,0.117647
6,200000007,0.0,0.0,27.0,0.0,125190.0,2.0,1.0,83,10,...,3.0,4.0,1.35,26.40,10.13,6.78,10.68,29.0,19.277108,0.113543
7,200000008,0.0,0.0,26.0,0.0,131122.0,1.0,0.0,97,2,...,0.0,6.0,0.00,45.36,0.00,0.00,15.68,33.0,15.463918,0.132695
8,200000009,0.0,0.0,25.0,0.0,108960.0,0.0,0.0,102,8,...,0.0,0.0,2.42,15.33,0.00,0.00,0.00,11.0,8.823529,0.139535
9,200000010,0.0,0.0,32.0,0.0,69370.0,0.0,0.0,98,1,...,0.0,0.0,16.42,62.38,0.00,0.00,0.00,47.0,15.306122,0.134063
10,200000011,0.0,0.0,44.0,1.0,181262.0,2.0,2.0,104,5,...,1.0,46.0,0.00,0.00,0.00,2.03,120.19,47.0,24.038462,0.142271
11,200000012,0.0,0.0,50.0,1.0,122830.0,1.0,1.0,105,4,...,0.0,22.0,3.78,0.00,0.00,0.00,57.71,25.0,12.380952,0.143639
12,200000013,0.0,0.0,34.0,1.0,116525.0,0.0,0.0,103,6,...,0.0,3.0,3.99,38.18,4.04,0.00,7.88,29.0,10.679612,0.140903
13,200000014,0.0,0.0,40.0,1.0,76881.0,0.0,0.0,111,12,...,3.0,3.0,0.00,27.71,0.00,6.48,8.28,22.0,10.810811,0.151847
14,200000015,1.0,0.0,25.0,0.0,72188.0,0.0,0.0,115,1,...,0.0,0.0,6.79,25.70,0.00,0.00,0.00,21.0,8.695652,0.157319
15,200000016,1.0,0.0,47.0,1.0,110287.0,1.0,0.0,106,4,...,0.0,0.0,0.00,26.01,0.00,0.00,0.00,15.0,5.660377,0.145007
16,200000017,0.0,0.0,29.0,0.0,102723.0,1.0,0.0,99,4,...,0.0,6.0,0.00,41.08,0.00,0.00,15.80,29.0,13.131313,0.135431
17,200000018,0.0,0.0,25.0,0.0,104505.0,0.0,0.0,102,4,...,0.0,1.0,0.00,20.11,0.00,0.00,2.44,13.0,6.862745,0.139535
18,200000019,0.0,1.0,26.0,1.0,72429.0,0.0,0.0,167,6,...,0.0,5.0,6.71,14.52,0.00,0.00,13.25,19.0,6.586826,0.228454
19,200000020,1.0,0.0,30.0,1.0,58207.0,0.0,0.0,101,6,...,3.0,0.0,8.22,29.09,0.00,6.78,0.00,25.0,8.910891,0.138167

In [96]:
lista_compras_promocion_marca_1 = np.empty(len(df))
lista_compras_promocion_marca_2 = np.empty(len(df))
lista_compras_promocion_marca_3 = np.empty(len(df))
lista_compras_promocion_marca_4 = np.empty(len(df))
lista_compras_promocion_marca_5 = np.empty(len(df))
lista_frec_compra_promociones_m1 = np.empty(len(df))
lista_frec_compra_promociones_m2 = np.empty(len(df))
lista_frec_compra_promociones_m3 = np.empty(len(df))
lista_frec_compra_promociones_m4 = np.empty(len(df))
lista_frec_compra_promociones_m5 = np.empty(len(df))

for i in range(len(df)): 
    if df.loc[i, 'MARCA'] == 0:
        lista_compras_promocion_marca_1[i] = 0
        lista_compras_promocion_marca_2[i] = 0
        lista_compras_promocion_marca_3[i] = 0
        lista_compras_promocion_marca_4[i] = 0
        lista_compras_promocion_marca_5[i] = 0
        lista_frec_compra_promociones_m1[i] = 0
        lista_frec_compra_promociones_m2[i] = 0
        lista_frec_compra_promociones_m3[i] = 0
        lista_frec_compra_promociones_m4[i] = 0
        lista_frec_compra_promociones_m5[i] = 0
    elif (df.loc[i, 'MARCA'] == 1 and df.loc[i, 'PROMOCION_1'] == 1):
        lista_compras_promocion_marca_1[i] = df.loc[i, 'CANTIDAD']
        lista_compras_promocion_marca_2[i] = 0
        lista_compras_promocion_marca_3[i] = 0
        lista_compras_promocion_marca_4[i] = 0
        lista_compras_promocion_marca_5[i] = 0
        lista_frec_compra_promociones_m1[i] = 1
        lista_frec_compra_promociones_m2[i] = 0
        lista_frec_compra_promociones_m3[i] = 0
        lista_frec_compra_promociones_m4[i] = 0
        lista_frec_compra_promociones_m5[i] = 0
    elif (df.loc[i, 'MARCA'] == 2 and df.loc[i, 'PROMOCION_2'] == 1):
        lista_compras_promocion_marca_1[i] = 0
        lista_compras_promocion_marca_2[i] = df.loc[i, 'CANTIDAD']
        lista_compras_promocion_marca_3[i] = 0
        lista_compras_promocion_marca_4[i] = 0
        lista_compras_promocion_marca_5[i] = 0
        lista_frec_compra_promociones_m1[i] = 0
        lista_frec_compra_promociones_m2[i] = 1
        lista_frec_compra_promociones_m3[i] = 0
        lista_frec_compra_promociones_m4[i] = 0
        lista_frec_compra_promociones_m5[i] = 0
    elif (df.loc[i, 'MARCA'] == 3 and df.loc[i, 'PROMOCION_3'] == 1):
        lista_compras_promocion_marca_1[i] = 0
        lista_compras_promocion_marca_2[i] = 0
        lista_compras_promocion_marca_3[i] = df.loc[i, 'CANTIDAD']
        lista_compras_promocion_marca_4[i] = 0
        lista_compras_promocion_marca_5[i] = 0
        lista_frec_compra_promociones_m1[i] = 0
        lista_frec_compra_promociones_m2[i] = 0 
        lista_frec_compra_promociones_m3[i] = 1
        lista_frec_compra_promociones_m4[i] = 0
        lista_frec_compra_promociones_m5[i] = 0
    elif (df.loc[i, 'MARCA'] == 4 and df.loc[i, 'PROMOCION_4'] == 1):
        lista_compras_promocion_marca_1[i] = 0
        lista_compras_promocion_marca_2[i] = 0
        lista_compras_promocion_marca_3[i] = 0
        lista_compras_promocion_marca_4[i] = df.loc[i, 'CANTIDAD']
        lista_compras_promocion_marca_5[i] = 0
        lista_frec_compra_promociones_m1[i] = 0
        lista_frec_compra_promociones_m2[i] = 0 
        lista_frec_compra_promociones_m3[i] = 0
        lista_frec_compra_promociones_m4[i] = 1
        lista_frec_compra_promociones_m5[i] = 0
    elif (df.loc[i, 'MARCA'] == 5 and df.loc[i, 'PROMOCION_5'] == 1):
        lista_compras_promocion_marca_1[i] = 0
        lista_compras_promocion_marca_2[i] = 0
        lista_compras_promocion_marca_3[i] = 0
        lista_compras_promocion_marca_4[i] = 0
        lista_compras_promocion_marca_5[i] = df.loc[i, 'CANTIDAD']
        lista_frec_compra_promociones_m1[i] = 0
        lista_frec_compra_promociones_m2[i] = 0 
        lista_frec_compra_promociones_m3[i] = 0
        lista_frec_compra_promociones_m4[i] = 0
        lista_frec_compra_promociones_m5[i] = 1
        
    else:
        lista_compras_promocion_marca_1[i] = 0
        lista_compras_promocion_marca_2[i] = 0
        lista_compras_promocion_marca_3[i] = 0
        lista_compras_promocion_marca_4[i] = 0
        lista_compras_promocion_marca_5[i] = 0
        lista_frec_compra_promociones_m1[i] = 0
        lista_frec_compra_promociones_m2[i] = 0
        lista_frec_compra_promociones_m3[i] = 0
        lista_frec_compra_promociones_m4[i] = 0
        lista_frec_compra_promociones_m5[i] = 0
        
df_lista_compras_promocion_marca_1 = pd.DataFrame(lista_compras_promocion_marca_1)
df_lista_compras_promocion_marca_2 = pd.DataFrame(lista_compras_promocion_marca_2)
df_lista_compras_promocion_marca_3 = pd.DataFrame(lista_compras_promocion_marca_3)
df_lista_compras_promocion_marca_4 = pd.DataFrame(lista_compras_promocion_marca_4)
df_lista_compras_promocion_marca_5 = pd.DataFrame(lista_compras_promocion_marca_5)
df_lista_frec_compra_promociones_m1 = pd.DataFrame(lista_frec_compra_promociones_m1)
df_lista_frec_compra_promociones_m2 = pd.DataFrame(lista_frec_compra_promociones_m2)
df_lista_frec_compra_promociones_m3 = pd.DataFrame(lista_frec_compra_promociones_m3)
df_lista_frec_compra_promociones_m4 = pd.DataFrame(lista_frec_compra_promociones_m4)
df_lista_frec_compra_promociones_m5 = pd.DataFrame(lista_frec_compra_promociones_m5)

header_df_lista_compras_promocion_marca_1 = ['Compras en Prom Marca 1']
header_df_lista_compras_promocion_marca_2 = ['Compras en Prom Marca 2']
header_df_lista_compras_promocion_marca_3 = ['Compras en Prom Marca 3']
header_df_lista_compras_promocion_marca_4 = ['Compras en Prom Marca 4']
header_df_lista_compras_promocion_marca_5 = ['Compras en Prom Marca 5']
header_df_lista_frec_compra_promociones_m1 = ['Ventas Efectivas Prom Marca 1']
header_df_lista_frec_compra_promociones_m2 = ['Ventas Efectivas Prom Marca 2']
header_df_lista_frec_compra_promociones_m3 = ['Ventas Efectivas Prom Marca 3']
header_df_lista_frec_compra_promociones_m4 = ['Ventas Efectivas Prom Marca 4']
header_df_lista_frec_compra_promociones_m5 = ['Ventas Efectivas Prom Marca 5']

df_lista_compras_promocion_marca_1.columns = header_df_lista_compras_promocion_marca_1
df_lista_compras_promocion_marca_2.columns = header_df_lista_compras_promocion_marca_2
df_lista_compras_promocion_marca_3.columns = header_df_lista_compras_promocion_marca_3
df_lista_compras_promocion_marca_4.columns = header_df_lista_compras_promocion_marca_4
df_lista_compras_promocion_marca_5.columns = header_df_lista_compras_promocion_marca_5
df_lista_frec_compra_promociones_m1.columns = header_df_lista_frec_compra_promociones_m1 
df_lista_frec_compra_promociones_m2.columns = header_df_lista_frec_compra_promociones_m2
df_lista_frec_compra_promociones_m3.columns = header_df_lista_frec_compra_promociones_m3
df_lista_frec_compra_promociones_m4.columns = header_df_lista_frec_compra_promociones_m4
df_lista_frec_compra_promociones_m5.columns = header_df_lista_frec_compra_promociones_m5

df_compras_y_promociones = pd.concat([df['ID'], df_lista_compras_promocion_marca_1, df_lista_compras_promocion_marca_2, df_lista_compras_promocion_marca_3, df_lista_compras_promocion_marca_4, df_lista_compras_promocion_marca_5, df_lista_frec_compra_promociones_m1, df_lista_frec_compra_promociones_m2, df_lista_frec_compra_promociones_m3, df_lista_frec_compra_promociones_m4, df_lista_frec_compra_promociones_m5], axis=1)

In [97]:
for i in range(len(df_compras_y_promociones)):
    df_compras_y_promociones.loc[i, 'Compras en Prom Marca 1'] = int(round(df_compras_y_promociones.loc[i, 'Compras en Prom Marca 1']))
    df_compras_y_promociones.loc[i, 'Compras en Prom Marca 2'] = int(round(df_compras_y_promociones.loc[i, 'Compras en Prom Marca 2']))
    df_compras_y_promociones.loc[i, 'Compras en Prom Marca 3'] = int(round(df_compras_y_promociones.loc[i, 'Compras en Prom Marca 3']))
    df_compras_y_promociones.loc[i, 'Compras en Prom Marca 4'] = int(round(df_compras_y_promociones.loc[i, 'Compras en Prom Marca 4']))
    df_compras_y_promociones.loc[i, 'Compras en Prom Marca 5'] = int(round(df_compras_y_promociones.loc[i, 'Compras en Prom Marca 5']))
    df_compras_y_promociones.loc[i, 'Ventas Efectivas Prom Marca 1'] = int(round(df_compras_y_promociones.loc[i, 'Ventas Efectivas Prom Marca 1']))
    df_compras_y_promociones.loc[i, 'Ventas Efectivas Prom Marca 2'] = int(round(df_compras_y_promociones.loc[i, 'Ventas Efectivas Prom Marca 2']))
    df_compras_y_promociones.loc[i, 'Ventas Efectivas Prom Marca 3'] = int(round(df_compras_y_promociones.loc[i, 'Ventas Efectivas Prom Marca 3']))
    df_compras_y_promociones.loc[i, 'Ventas Efectivas Prom Marca 4'] = int(round(df_compras_y_promociones.loc[i, 'Ventas Efectivas Prom Marca 4']))
    df_compras_y_promociones.loc[i, 'Ventas Efectivas Prom Marca 5'] = int(round(df_compras_y_promociones.loc[i, 'Ventas Efectivas Prom Marca 5']))

In [98]:
df_compras_y_promociones.head(20)

,ID,Compras en Prom Marca 1,Compras en Prom Marca 2,Compras en Prom Marca 3,Compras en Prom Marca 4,Compras en Prom Marca 5,Ventas Efectivas Prom Marca 1,Ventas Efectivas Prom Marca 2,Ventas Efectivas Prom Marca 3,Ventas Efectivas Prom Marca 4,Ventas Efectivas Prom Marca 5
0,200000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,200000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,200000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,200000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,200000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,200000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,200000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,200000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,200000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,200000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,200000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,200000001,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
12,200000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,200000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,200000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,200000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,200000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,200000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,200000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,200000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [99]:
#El primero es la cantidad de elementos vendidos en una promoción, y el segundo, la realizacion de la venta en promociones (puede ser de 1 o mas elemntos)
df_compras_y_promociones['Compras en Prom'] = df_compras_y_promociones['Compras en Prom Marca 1'] + df_compras_y_promociones['Compras en Prom Marca 2'] + df_compras_y_promociones['Compras en Prom Marca 3'] + df_compras_y_promociones['Compras en Prom Marca 4'] + df_compras_y_promociones['Compras en Prom Marca 5']
df_compras_y_promociones['Ventas Efectivas en Prom'] = df_compras_y_promociones['Ventas Efectivas Prom Marca 1'] + df_compras_y_promociones['Ventas Efectivas Prom Marca 2'] + df_compras_y_promociones['Ventas Efectivas Prom Marca 3'] + df_compras_y_promociones['Ventas Efectivas Prom Marca 4'] + df_compras_y_promociones['Ventas Efectivas Prom Marca 5']
df_compras_y_promociones

,ID,Compras en Prom Marca 1,Compras en Prom Marca 2,Compras en Prom Marca 3,Compras en Prom Marca 4,Compras en Prom Marca 5,Ventas Efectivas Prom Marca 1,Ventas Efectivas Prom Marca 2,Ventas Efectivas Prom Marca 3,Ventas Efectivas Prom Marca 4,Ventas Efectivas Prom Marca 5,Compras en Prom,Ventas Efectivas en Prom
0,200000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,200000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,200000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,200000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,200000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
58688,200000500,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
58689,200000500,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
58690,200000500,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
58691,200000500,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
58692,200000500,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [100]:
df_compras_y_promociones = df_compras_y_promociones.groupby(['ID'],as_index=False).sum()
df_compras_y_promociones = df_compras_y_promociones.drop(['ID'], axis=1)
df_final = pd.concat([df_final, df_compras_y_promociones], axis=1)
df_final.head(30)

,ID,SEXO,ESTADO_CIVIL,EDAD,EDUCACION,INGRESO,OCUPACION,TAMAÑO_CIUDAD,Cantidad de Visitas,Dias sin Visita,...,Compras en Prom Marca 3,Compras en Prom Marca 4,Compras en Prom Marca 5,Ventas Efectivas Prom Marca 1,Ventas Efectivas Prom Marca 2,Ventas Efectivas Prom Marca 3,Ventas Efectivas Prom Marca 4,Ventas Efectivas Prom Marca 5,Compras en Prom,Ventas Efectivas en Prom
0,200000001,0.0,0.0,47.0,1.0,110866.0,1.0,0.0,101,4,...,0.0,3.0,1.0,0.0,1.0,0.0,1.0,1.0,7.0,3.0
1,200000002,1.0,1.0,52.0,2.0,159052.0,2.0,1.0,87,2,...,0.0,4.0,0.0,0.0,0.0,0.0,3.0,0.0,4.0,3.0
2,200000003,0.0,0.0,28.0,0.0,113212.0,1.0,0.0,97,7,...,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,5.0,3.0
3,200000004,0.0,0.0,37.0,1.0,119602.0,0.0,0.0,85,6,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0
4,200000005,0.0,0.0,49.0,1.0,121466.0,1.0,2.0,111,2,...,0.0,0.0,3.0,0.0,0.0,0.0,0.0,1.0,3.0,1.0
5,200000006,0.0,0.0,39.0,1.0,112347.0,1.0,2.0,86,4,...,0.0,0.0,2.0,1.0,1.0,0.0,0.0,1.0,9.0,3.0
6,200000007,0.0,0.0,27.0,0.0,125190.0,2.0,1.0,83,10,...,0.0,0.0,0.0,1.0,4.0,0.0,0.0,0.0,8.0,5.0
7,200000008,0.0,0.0,26.0,0.0,131122.0,1.0,0.0,97,2,...,0.0,0.0,2.0,0.0,4.0,0.0,0.0,1.0,10.0,5.0
8,200000009,0.0,0.0,25.0,0.0,108960.0,0.0,0.0,102,8,...,0.0,0.0,0.0,1.0,3.0,0.0,0.0,0.0,6.0,4.0
9,200000010,0.0,0.0,32.0,0.0,69370.0,0.0,0.0,98,1,...,0.0,0.0,0.0,2.0,4.0,0.0,0.0,0.0,19.0,6.0
10,200000011,0.0,0.0,44.0,1.0,181262.0,2.0,2.0,104,5,...,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,2.0,2.0
11,200000012,0.0,0.0,50.0,1.0,122830.0,1.0,1.0,105,4,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,4.0,2.0
12,200000013,0.0,0.0,34.0,1.0,116525.0,0.0,0.0,103,6,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,3.0,2.0
13,200000014,0.0,0.0,40.0,1.0,76881.0,0.0,0.0,111,12,...,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,6.0,2.0
14,200000015,1.0,0.0,25.0,0.0,72188.0,0.0,0.0,115,1,...,0.0,0.0,0.0,1.0,6.0,0.0,0.0,0.0,13.0,7.0
15,200000016,1.0,0.0,47.0,1.0,110287.0,1.0,0.0,106,4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,200000017,0.0,0.0,29.0,0.0,102723.0,1.0,0.0,99,4,...,0.0,0.0,2.0,0.0,1.0,0.0,0.0,2.0,5.0,3.0
17,200000018,0.0,0.0,25.0,0.0,104505.0,0.0,0.0,102,4,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,4.0,2.0
18,200000019,0.0,1.0,26.0,1.0,72429.0,0.0,0.0,167,6,...,0.0,0.0,0.0,2.0,3.0,0.0,0.0,0.0,6.0,5.0
19,200000020,1.0,0.0,30.0,1.0,58207.0,0.0,0.0,101,6,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2.0,1.0
20,200000021,0.0,0.0,63.0,2.0,135754.0,1.0,0.0,104,7,...,0.0,3.0,0.0,0.0,0.0,0.0,1.0,0.0,3.0,1.0
21,200000022,0.0,0.0,32.0,0.0,121347.0,1.0,1.0,94,14,...,0.0,5.0,0.0,1.0,1.0,0.0,2.0,0.0,9.0,4.0
22,200000023,0.0,0.0,48.0,1.0,94868.0,0.0,0.0,137,5,...,0.0,0.0,0.0,2.0,1.0,0.0,0.0,0.0,6.0,3.0
23,200000024,1.0,1.0,32.0,1.0,88428.0,0.0,0.0,90,4,...,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,9.0,4.0
24,200000025,0.0,0.0,24.0,0.0,107633.0,1.0,1.0,122,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,200000026,0.0,0.0,37.0,1.0,170146.0,2.0,0.0,101,1,...,0.0,0.0,3.0,1.0,0.0,0.0,0.0,1.0,6.0,2.0
26,200000027,1.0,1.0,33.0,1.0,112422.0,1.0,1.0,123,4,...,0.0,0.0,1.0,2.0,1.0,0.0,0.0,1.0,9.0,4.0
27,200000028,1.0,0.0,35.0,1.0,53608.0,0.0,0.0,93,9,...,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,14.0,5.0
28,200000029,1.0,0.0,50.0,1.0,119068.0,1.0,0.0,103,11,...,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,6.0,2.0
29,200000030,0.0,1.0,24.0,1.0,81210.0,0.0,0.0,101,7,...,0.0,0.0,0.0,1.0,23.0,0.0,0.0,0.0,83.0,24.0

In [101]:
df_num_prom_Xcliente = df[['ID', 'PROMOCION_1', 'PROMOCION_2', 'PROMOCION_3', 'PROMOCION_4', 'PROMOCION_5']]
df_num_prom_Xcliente = df_num_prom_Xcliente.groupby(['ID'],as_index=False).sum()
header_df_num_prom_Xcliente = ['Promociones durante Visitas Marca 1', 'Promociones durante Visitas Marca 2', 'Promociones durante Visitas Marca 3', 'Promociones durante Visitas Marca 4', 'Promociones durante Visitas Marca 5']
df_num_prom_Xcliente = df_num_prom_Xcliente.drop(['ID'], axis=1)
df_num_prom_Xcliente.columns = header_df_num_prom_Xcliente
df_num_prom_Xcliente['Total Promociones en Visitas'] = df_num_prom_Xcliente['Promociones durante Visitas Marca 1'] + df_num_prom_Xcliente['Promociones durante Visitas Marca 2'] + df_num_prom_Xcliente['Promociones durante Visitas Marca 3'] + df_num_prom_Xcliente['Promociones durante Visitas Marca 4'] + df_num_prom_Xcliente['Promociones durante Visitas Marca 5']
df_num_prom_Xcliente

,Promociones durante Visitas Marca 1,Promociones durante Visitas Marca 2,Promociones durante Visitas Marca 3,Promociones durante Visitas Marca 4,Promociones durante Visitas Marca 5,Total Promociones en Visitas
0,40,36,6,15,5,102
1,20,26,2,14,3,65
2,28,28,2,12,2,72
3,28,26,3,12,3,72
4,25,25,2,13,2,67
...,...,...,...,...,...,...
495,45,41,5,16,4,111
496,44,33,7,17,5,106
497,42,34,6,12,4,98
498,41,36,3,11,5,96
499,45,47,5,16,3,116

In [102]:
df_final = pd.concat([df_final, df_num_prom_Xcliente], axis=1)
df_final

,ID,SEXO,ESTADO_CIVIL,EDAD,EDUCACION,INGRESO,OCUPACION,TAMAÑO_CIUDAD,Cantidad de Visitas,Dias sin Visita,...,Ventas Efectivas Prom Marca 4,Ventas Efectivas Prom Marca 5,Compras en Prom,Ventas Efectivas en Prom,Promociones durante Visitas Marca 1,Promociones durante Visitas Marca 2,Promociones durante Visitas Marca 3,Promociones durante Visitas Marca 4,Promociones durante Visitas Marca 5,Total Promociones en Visitas
0,200000001,0.0,0.0,47.0,1.0,110866.0,1.0,0.0,101,4,...,1.0,1.0,7.0,3.0,40,36,6,15,5,102
1,200000002,1.0,1.0,52.0,2.0,159052.0,2.0,1.0,87,2,...,3.0,0.0,4.0,3.0,20,26,2,14,3,65
2,200000003,0.0,0.0,28.0,0.0,113212.0,1.0,0.0,97,7,...,0.0,0.0,5.0,3.0,28,28,2,12,2,72
3,200000004,0.0,0.0,37.0,1.0,119602.0,0.0,0.0,85,6,...,0.0,0.0,1.0,1.0,28,26,3,12,3,72
4,200000005,0.0,0.0,49.0,1.0,121466.0,1.0,2.0,111,2,...,0.0,1.0,3.0,1.0,25,25,2,13,2,67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,200000496,1.0,1.0,26.0,1.0,71021.0,0.0,0.0,120,8,...,0.0,1.0,15.0,7.0,45,41,5,16,4,111
496,200000497,0.0,0.0,60.0,2.0,89374.0,0.0,0.0,120,9,...,2.0,0.0,70.0,12.0,44,33,7,17,5,106
497,200000498,1.0,1.0,29.0,1.0,114784.0,1.0,0.0,131,2,...,0.0,0.0,42.0,12.0,42,34,6,12,4,98
498,200000499,1.0,0.0,35.0,1.0,73266.0,0.0,0.0,106,4,...,0.0,1.0,49.0,16.0,41,36,3,11,5,96
499,200000500,0.0,0.0,42.0,1.0,120946.0,1.0,0.0,124,5,...,0.0,0.0,56.0,7.0,45,47,5,16,3,116

In [103]:
df_final['% Compras en Promociones Marca 1'] = (df_final['Ventas Efectivas Prom Marca 1']*100)/df_final['Cantidad Ventas Efectivas']
df_final['% Compras en Promociones Marca 2'] = (df_final['Ventas Efectivas Prom Marca 2']*100)/df_final['Cantidad Ventas Efectivas']
df_final['% Compras en Promociones Marca 3'] = (df_final['Ventas Efectivas Prom Marca 3']*100)/df_final['Cantidad Ventas Efectivas']
df_final['% Compras en Promociones Marca 4'] = (df_final['Ventas Efectivas Prom Marca 4']*100)/df_final['Cantidad Ventas Efectivas']
df_final['% Compras en Promociones Marca 5'] = (df_final['Ventas Efectivas Prom Marca 5']*100)/df_final['Cantidad Ventas Efectivas']
df_final['% Compras en Promociones'] = (df_final['Ventas Efectivas en Prom']*100)/df_final['Cantidad Ventas Efectivas']
df_final.head(20)

,ID,SEXO,ESTADO_CIVIL,EDAD,EDUCACION,INGRESO,OCUPACION,TAMAÑO_CIUDAD,Cantidad de Visitas,Dias sin Visita,...,Promociones durante Visitas Marca 3,Promociones durante Visitas Marca 4,Promociones durante Visitas Marca 5,Total Promociones en Visitas,% Compras en Promociones Marca 1,% Compras en Promociones Marca 2,% Compras en Promociones Marca 3,% Compras en Promociones Marca 4,% Compras en Promociones Marca 5,% Compras en Promociones
0,200000001,0.0,0.0,47.0,1.0,110866.0,1.0,0.0,101,4,...,6,15,5,102,0.000000,11.111111,0.0,11.111111,11.111111,33.333333
1,200000002,1.0,1.0,52.0,2.0,159052.0,2.0,1.0,87,2,...,2,14,3,65,0.000000,0.000000,0.0,27.272727,0.000000,27.272727
2,200000003,0.0,0.0,28.0,0.0,113212.0,1.0,0.0,97,7,...,2,12,2,72,0.000000,30.000000,0.0,0.000000,0.000000,30.000000
3,200000004,0.0,0.0,37.0,1.0,119602.0,0.0,0.0,85,6,...,3,12,3,72,0.000000,9.090909,0.0,0.000000,0.000000,9.090909
4,200000005,0.0,0.0,49.0,1.0,121466.0,1.0,2.0,111,2,...,2,13,2,67,0.000000,0.000000,0.0,0.000000,7.692308,7.692308
5,200000006,0.0,0.0,39.0,1.0,112347.0,1.0,2.0,86,4,...,2,9,5,81,10.000000,10.000000,0.0,0.000000,10.000000,30.000000
6,200000007,0.0,0.0,27.0,0.0,125190.0,2.0,1.0,83,10,...,5,9,4,84,6.250000,25.000000,0.0,0.000000,0.000000,31.250000
7,200000008,0.0,0.0,26.0,0.0,131122.0,1.0,0.0,97,2,...,4,10,3,68,0.000000,26.666667,0.0,0.000000,6.666667,33.333333
8,200000009,0.0,0.0,25.0,0.0,108960.0,0.0,0.0,102,8,...,7,10,4,92,11.111111,33.333333,0.0,0.000000,0.000000,44.444444
9,200000010,0.0,0.0,32.0,0.0,69370.0,0.0,0.0,98,1,...,2,11,4,79,13.333333,26.666667,0.0,0.000000,0.000000,40.000000
10,200000011,0.0,0.0,44.0,1.0,181262.0,2.0,2.0,104,5,...,4,14,4,97,0.000000,0.000000,0.0,4.000000,4.000000,8.000000
11,200000012,0.0,0.0,50.0,1.0,122830.0,1.0,1.0,105,4,...,3,16,4,91,7.692308,0.000000,0.0,0.000000,7.692308,15.384615
12,200000013,0.0,0.0,34.0,1.0,116525.0,0.0,0.0,103,6,...,5,12,3,87,0.000000,9.090909,0.0,0.000000,9.090909,18.181818
13,200000014,0.0,0.0,40.0,1.0,76881.0,0.0,0.0,111,12,...,4,18,4,90,0.000000,16.666667,0.0,0.000000,0.000000,16.666667
14,200000015,1.0,0.0,25.0,0.0,72188.0,0.0,0.0,115,1,...,6,11,4,95,10.000000,60.000000,0.0,0.000000,0.000000,70.000000
15,200000016,1.0,0.0,47.0,1.0,110287.0,1.0,0.0,106,4,...,3,15,4,86,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
16,200000017,0.0,0.0,29.0,0.0,102723.0,1.0,0.0,99,4,...,5,9,3,83,0.000000,7.692308,0.0,0.000000,15.384615,23.076923
17,200000018,0.0,0.0,25.0,0.0,104505.0,0.0,0.0,102,4,...,4,11,5,97,0.000000,14.285714,0.0,0.000000,14.285714,28.571429
18,200000019,0.0,1.0,26.0,1.0,72429.0,0.0,0.0,167,6,...,10,16,5,154,18.181818,27.272727,0.0,0.000000,0.000000,45.454545
19,200000020,1.0,0.0,30.0,1.0,58207.0,0.0,0.0,101,6,...,3,14,2,85,0.000000,11.111111,0.0,0.000000,0.000000,11.111111

In [104]:
df_final['% Promociones en Visitas Marca 1'] = (df_final['Promociones durante Visitas Marca 1']*100)/df_final['Cantidad de Visitas']
df_final['% Promociones en Visitas Marca 2'] = (df_final['Promociones durante Visitas Marca 2']*100)/df_final['Cantidad de Visitas']
df_final['% Promociones en Visitas Marca 3'] = (df_final['Promociones durante Visitas Marca 3']*100)/df_final['Cantidad de Visitas']
df_final['% Promociones en Visitas Marca 4'] = (df_final['Promociones durante Visitas Marca 4']*100)/df_final['Cantidad de Visitas']
df_final['% Promociones en Visitas Marca 5'] = (df_final['Promociones durante Visitas Marca 5']*100)/df_final['Cantidad de Visitas']
df_final['Proporcion de Promociones por Visitas'] = (df_final['Total Promociones en Visitas']*100)/df_final['Cantidad de Visitas']
df_final.head(20)

,ID,SEXO,ESTADO_CIVIL,EDAD,EDUCACION,INGRESO,OCUPACION,TAMAÑO_CIUDAD,Cantidad de Visitas,Dias sin Visita,...,% Compras en Promociones Marca 3,% Compras en Promociones Marca 4,% Compras en Promociones Marca 5,% Compras en Promociones,% Promociones en Visitas Marca 1,% Promociones en Visitas Marca 2,% Promociones en Visitas Marca 3,% Promociones en Visitas Marca 4,% Promociones en Visitas Marca 5,Proporcion de Promociones por Visitas
0,200000001,0.0,0.0,47.0,1.0,110866.0,1.0,0.0,101,4,...,0.0,11.111111,11.111111,33.333333,39.603960,35.643564,5.940594,14.851485,4.950495,100.990099
1,200000002,1.0,1.0,52.0,2.0,159052.0,2.0,1.0,87,2,...,0.0,27.272727,0.000000,27.272727,22.988506,29.885057,2.298851,16.091954,3.448276,74.712644
2,200000003,0.0,0.0,28.0,0.0,113212.0,1.0,0.0,97,7,...,0.0,0.000000,0.000000,30.000000,28.865979,28.865979,2.061856,12.371134,2.061856,74.226804
3,200000004,0.0,0.0,37.0,1.0,119602.0,0.0,0.0,85,6,...,0.0,0.000000,0.000000,9.090909,32.941176,30.588235,3.529412,14.117647,3.529412,84.705882
4,200000005,0.0,0.0,49.0,1.0,121466.0,1.0,2.0,111,2,...,0.0,0.000000,7.692308,7.692308,22.522523,22.522523,1.801802,11.711712,1.801802,60.360360
5,200000006,0.0,0.0,39.0,1.0,112347.0,1.0,2.0,86,4,...,0.0,0.000000,10.000000,30.000000,39.534884,36.046512,2.325581,10.465116,5.813953,94.186047
6,200000007,0.0,0.0,27.0,0.0,125190.0,2.0,1.0,83,10,...,0.0,0.000000,0.000000,31.250000,38.554217,40.963855,6.024096,10.843373,4.819277,101.204819
7,200000008,0.0,0.0,26.0,0.0,131122.0,1.0,0.0,97,2,...,0.0,0.000000,6.666667,33.333333,25.773196,26.804124,4.123711,10.309278,3.092784,70.103093
8,200000009,0.0,0.0,25.0,0.0,108960.0,0.0,0.0,102,8,...,0.0,0.000000,0.000000,44.444444,37.254902,32.352941,6.862745,9.803922,3.921569,90.196078
9,200000010,0.0,0.0,32.0,0.0,69370.0,0.0,0.0,98,1,...,0.0,0.000000,0.000000,40.000000,30.612245,32.653061,2.040816,11.224490,4.081633,80.612245
10,200000011,0.0,0.0,44.0,1.0,181262.0,2.0,2.0,104,5,...,0.0,4.000000,4.000000,8.000000,40.384615,31.730769,3.846154,13.461538,3.846154,93.269231
11,200000012,0.0,0.0,50.0,1.0,122830.0,1.0,1.0,105,4,...,0.0,0.000000,7.692308,15.384615,34.285714,30.476190,2.857143,15.238095,3.809524,86.666667
12,200000013,0.0,0.0,34.0,1.0,116525.0,0.0,0.0,103,6,...,0.0,0.000000,9.090909,18.181818,34.951456,30.097087,4.854369,11.650485,2.912621,84.466019
13,200000014,0.0,0.0,40.0,1.0,76881.0,0.0,0.0,111,12,...,0.0,0.000000,0.000000,16.666667,29.729730,27.927928,3.603604,16.216216,3.603604,81.081081
14,200000015,1.0,0.0,25.0,0.0,72188.0,0.0,0.0,115,1,...,0.0,0.000000,0.000000,70.000000,34.782609,29.565217,5.217391,9.565217,3.478261,82.608696
15,200000016,1.0,0.0,47.0,1.0,110287.0,1.0,0.0,106,4,...,0.0,0.000000,0.000000,0.000000,33.018868,27.358491,2.830189,14.150943,3.773585,81.132075
16,200000017,0.0,0.0,29.0,0.0,102723.0,1.0,0.0,99,4,...,0.0,0.000000,15.384615,23.076923,33.333333,33.333333,5.050505,9.090909,3.030303,83.838384
17,200000018,0.0,0.0,25.0,0.0,104505.0,0.0,0.0,102,4,...,0.0,0.000000,14.285714,28.571429,40.196078,35.294118,3.921569,10.784314,4.901961,95.098039
18,200000019,0.0,1.0,26.0,1.0,72429.0,0.0,0.0,167,6,...,0.0,0.000000,0.000000,45.454545,37.125749,36.526946,5.988024,9.580838,2.994012,92.215569
19,200000020,1.0,0.0,30.0,1.0,58207.0,0.0,0.0,101,6,...,0.0,0.000000,0.000000,11.111111,32.673267,32.673267,2.970297,13.861386,1.980198,84.158416

In [105]:
indicador_bajadas_precio_marca_1 = np.empty(len(df))
indicador_bajadas_precio_marca_2 = np.empty(len(df))
indicador_bajadas_precio_marca_3 = np.empty(len(df))
indicador_bajadas_precio_marca_4 = np.empty(len(df))
indicador_bajadas_precio_marca_5 = np.empty(len(df))

indicador_subidas_precio_marca_1 = np.empty(len(df))
indicador_subidas_precio_marca_2 = np.empty(len(df))
indicador_subidas_precio_marca_3 = np.empty(len(df))
indicador_subidas_precio_marca_4 = np.empty(len(df))
indicador_subidas_precio_marca_5 = np.empty(len(df))

indicador_iguales_precio_marca_1 = np.empty(len(df))
indicador_iguales_precio_marca_2 = np.empty(len(df))
indicador_iguales_precio_marca_3 = np.empty(len(df))
indicador_iguales_precio_marca_4 = np.empty(len(df))
indicador_iguales_precio_marca_5 = np.empty(len(df))

cantidad_variacion_precio_marca_1 = np.empty(len(df))
cantidad_variacion_precio_marca_2 = np.empty(len(df))
cantidad_variacion_precio_marca_3 = np.empty(len(df))
cantidad_variacion_precio_marca_4 = np.empty(len(df))
cantidad_variacion_precio_marca_5 = np.empty(len(df))

for i in range(len(df)): 
    if i == 0:
        indicador_bajadas_precio_marca_1[i] = 0
        indicador_bajadas_precio_marca_2[i] = 0
        indicador_bajadas_precio_marca_3[i] = 0
        indicador_bajadas_precio_marca_4[i] = 0
        indicador_bajadas_precio_marca_5[i] = 0

        indicador_subidas_precio_marca_1[i] = 0
        indicador_subidas_precio_marca_2[i] = 0
        indicador_subidas_precio_marca_3[i] = 0
        indicador_subidas_precio_marca_4[i] = 0
        indicador_subidas_precio_marca_5[i] = 0

        indicador_iguales_precio_marca_1[i] = 0
        indicador_iguales_precio_marca_2[i] = 0
        indicador_iguales_precio_marca_3[i] = 0
        indicador_iguales_precio_marca_4[i] = 0
        indicador_iguales_precio_marca_5[i] = 0

        cantidad_variacion_precio_marca_1[i] = 0
        cantidad_variacion_precio_marca_2[i] = 0
        cantidad_variacion_precio_marca_3[i] = 0
        cantidad_variacion_precio_marca_4[i] = 0
        cantidad_variacion_precio_marca_5[i] = 0
        
    else:
        cantidad_variacion_precio_marca_1[i] = df.loc[i, 'PRECIO_1'] - df.loc[i-1, 'PRECIO_1']
        cantidad_variacion_precio_marca_2[i] = df.loc[i, 'PRECIO_2'] - df.loc[i-1, 'PRECIO_2']
        cantidad_variacion_precio_marca_3[i] = df.loc[i, 'PRECIO_3'] - df.loc[i-1, 'PRECIO_3']
        cantidad_variacion_precio_marca_4[i] = df.loc[i, 'PRECIO_4'] - df.loc[i-1, 'PRECIO_4']
        cantidad_variacion_precio_marca_5[i] = df.loc[i, 'PRECIO_5'] - df.loc[i-1, 'PRECIO_5']
        
        if (cantidad_variacion_precio_marca_1[i] < 0):
            indicador_bajadas_precio_marca_1[i] = 1
            indicador_iguales_precio_marca_1[i] = 0
            indicador_subidas_precio_marca_1[i] = 0
        elif (cantidad_variacion_precio_marca_1[i] == 0):
            indicador_bajadas_precio_marca_1[i] = 0
            indicador_iguales_precio_marca_1[i] = 1
            indicador_subidas_precio_marca_1[i] = 0
        else:
            indicador_bajadas_precio_marca_1[i] = 0
            indicador_iguales_precio_marca_1[i] = 0
            indicador_subidas_precio_marca_1[i] = 1
            
        if (cantidad_variacion_precio_marca_2[i] < 0):
            indicador_bajadas_precio_marca_2[i] = 1
            indicador_iguales_precio_marca_2[i] = 0
            indicador_subidas_precio_marca_2[i] = 0
        elif (cantidad_variacion_precio_marca_2[i] == 0):
            indicador_bajadas_precio_marca_2[i] = 0
            indicador_iguales_precio_marca_2[i] = 1
            indicador_subidas_precio_marca_2[i] = 0
        else:
            indicador_bajadas_precio_marca_2[i] = 0
            indicador_iguales_precio_marca_2[i] = 0
            indicador_subidas_precio_marca_2[i] = 1
            
        if (cantidad_variacion_precio_marca_3[i] < 0):
            indicador_bajadas_precio_marca_3[i] = 1
            indicador_iguales_precio_marca_3[i] = 0
            indicador_subidas_precio_marca_3[i] = 0
        elif (cantidad_variacion_precio_marca_3[i] == 0):
            indicador_bajadas_precio_marca_3[i] = 0
            indicador_iguales_precio_marca_3[i] = 1
            indicador_subidas_precio_marca_3[i] = 0
        else:
            indicador_bajadas_precio_marca_3[i] = 0
            indicador_iguales_precio_marca_3[i] = 0
            indicador_subidas_precio_marca_3[i] = 1
            
        if (cantidad_variacion_precio_marca_4[i] < 0):
            indicador_bajadas_precio_marca_4[i] = 1
            indicador_iguales_precio_marca_4[i] = 0
            indicador_subidas_precio_marca_4[i] = 0
        elif (cantidad_variacion_precio_marca_4[i] == 0):
            indicador_bajadas_precio_marca_4[i] = 0
            indicador_iguales_precio_marca_4[i] = 1
            indicador_subidas_precio_marca_4[i] = 0
        else:
            indicador_bajadas_precio_marca_4[i] = 0
            indicador_iguales_precio_marca_4[i] = 0
            indicador_subidas_precio_marca_4[i] = 1
            
        if (cantidad_variacion_precio_marca_5[i] < 0):
            indicador_bajadas_precio_marca_5[i] = 1
            indicador_iguales_precio_marca_5[i] = 0
            indicador_subidas_precio_marca_5[i] = 0
        elif (cantidad_variacion_precio_marca_5[i] == 0):
            indicador_bajadas_precio_marca_5[i] = 0
            indicador_iguales_precio_marca_5[i] = 1
            indicador_subidas_precio_marca_5[i] = 0
        else:
            indicador_bajadas_precio_marca_5[i] = 0
            indicador_iguales_precio_marca_5[i] = 0
            indicador_subidas_precio_marca_5[i] = 1
            
            
            
            
indicador_bajadas_precio_marca_1 = pd.DataFrame(indicador_bajadas_precio_marca_1)
indicador_bajadas_precio_marca_2 = pd.DataFrame(indicador_bajadas_precio_marca_2)
indicador_bajadas_precio_marca_3 = pd.DataFrame(indicador_bajadas_precio_marca_3)
indicador_bajadas_precio_marca_4 = pd.DataFrame(indicador_bajadas_precio_marca_4)
indicador_bajadas_precio_marca_5 = pd.DataFrame(indicador_bajadas_precio_marca_5)
indicador_subidas_precio_marca_1 = pd.DataFrame(indicador_subidas_precio_marca_1)
indicador_subidas_precio_marca_2 = pd.DataFrame(indicador_subidas_precio_marca_2)
indicador_subidas_precio_marca_3 = pd.DataFrame(indicador_subidas_precio_marca_3)
indicador_subidas_precio_marca_4 = pd.DataFrame(indicador_subidas_precio_marca_4)
indicador_subidas_precio_marca_5 = pd.DataFrame(indicador_subidas_precio_marca_5)
indicador_iguales_precio_marca_1 = pd.DataFrame(indicador_iguales_precio_marca_1)
indicador_iguales_precio_marca_2 = pd.DataFrame(indicador_iguales_precio_marca_2)
indicador_iguales_precio_marca_3 = pd.DataFrame(indicador_iguales_precio_marca_3)
indicador_iguales_precio_marca_4 = pd.DataFrame(indicador_iguales_precio_marca_4)
indicador_iguales_precio_marca_5 = pd.DataFrame(indicador_iguales_precio_marca_5)
cantidad_variacion_precio_marca_1 = pd.DataFrame(cantidad_variacion_precio_marca_1)
cantidad_variacion_precio_marca_2 = pd.DataFrame(cantidad_variacion_precio_marca_2)
cantidad_variacion_precio_marca_3 = pd.DataFrame(cantidad_variacion_precio_marca_3)
cantidad_variacion_precio_marca_4 = pd.DataFrame(cantidad_variacion_precio_marca_4)
cantidad_variacion_precio_marca_5 = pd.DataFrame(cantidad_variacion_precio_marca_5)

header_indicador_bajadas_precio_marca_1 = ['Indicador Bajas de Precio Marca 1']
header_indicador_bajadas_precio_marca_2 = ['Indicador Bajas de Precio Marca 2']
header_indicador_bajadas_precio_marca_3 = ['Indicador Bajas de Precio Marca 3']
header_indicador_bajadas_precio_marca_4 = ['Indicador Bajas de Precio Marca 4']
header_indicador_bajadas_precio_marca_5 = ['Indicador Bajas de Precio Marca 5']
header_indicador_subidas_precio_marca_1 = ['Indicador Subidas de Precio Marca 1']
header_indicador_subidas_precio_marca_2 = ['Indicador Subidas de Precio Marca 2']
header_indicador_subidas_precio_marca_3 = ['Indicador Subidas de Precio Marca 3']
header_indicador_subidas_precio_marca_4 = ['Indicador Subidas de Precio Marca 4']
header_indicador_subidas_precio_marca_5 = ['Indicador Subidas de Precio Marca 5']
header_indicador_iguales_precio_marca_1 = ['Indicador Sostenimiento de Precio Marca 1']
header_indicador_iguales_precio_marca_2 = ['Indicador Sostenimiento de Precio Marca 2']
header_indicador_iguales_precio_marca_3 = ['Indicador Sostenimiento de Precio Marca 3']
header_indicador_iguales_precio_marca_4 = ['Indicador Sostenimiento de Precio Marca 4']
header_indicador_iguales_precio_marca_5 = ['Indicador Sostenimiento de Precio Marca 5']
header_cantidad_variacion_precio_marca_1 = ['Cantidad de Variación del Precio Marca 1']
header_cantidad_variacion_precio_marca_2 = ['Cantidad de Variación del Precio Marca 2']
header_cantidad_variacion_precio_marca_3 = ['Cantidad de Variación del Precio Marca 3']
header_cantidad_variacion_precio_marca_4 = ['Cantidad de Variación del Precio Marca 4']
header_cantidad_variacion_precio_marca_5 = ['Cantidad de Variación del Precio Marca 5']

indicador_bajadas_precio_marca_1.columns = header_indicador_bajadas_precio_marca_1
indicador_bajadas_precio_marca_2.columns = header_indicador_bajadas_precio_marca_2
indicador_bajadas_precio_marca_3.columns = header_indicador_bajadas_precio_marca_3
indicador_bajadas_precio_marca_4.columns = header_indicador_bajadas_precio_marca_4
indicador_bajadas_precio_marca_5.columns = header_indicador_bajadas_precio_marca_5
indicador_subidas_precio_marca_1.columns = header_indicador_subidas_precio_marca_1
indicador_subidas_precio_marca_2.columns = header_indicador_subidas_precio_marca_2
indicador_subidas_precio_marca_3.columns = header_indicador_subidas_precio_marca_3
indicador_subidas_precio_marca_4.columns = header_indicador_subidas_precio_marca_4
indicador_subidas_precio_marca_5.columns = header_indicador_subidas_precio_marca_5
indicador_iguales_precio_marca_1.columns = header_indicador_iguales_precio_marca_1
indicador_iguales_precio_marca_2.columns = header_indicador_iguales_precio_marca_2
indicador_iguales_precio_marca_3.columns = header_indicador_iguales_precio_marca_3
indicador_iguales_precio_marca_4.columns = header_indicador_iguales_precio_marca_4
indicador_iguales_precio_marca_5.columns = header_indicador_iguales_precio_marca_5
cantidad_variacion_precio_marca_1.columns = header_cantidad_variacion_precio_marca_1 
cantidad_variacion_precio_marca_2.columns = header_cantidad_variacion_precio_marca_2 
cantidad_variacion_precio_marca_3.columns = header_cantidad_variacion_precio_marca_3 
cantidad_variacion_precio_marca_4.columns = header_cantidad_variacion_precio_marca_4 
cantidad_variacion_precio_marca_5.columns = header_cantidad_variacion_precio_marca_5 

df_variacion_precio = pd.concat([df['ID'], cantidad_variacion_precio_marca_1, indicador_bajadas_precio_marca_1, indicador_subidas_precio_marca_1, indicador_iguales_precio_marca_1, cantidad_variacion_precio_marca_2, indicador_bajadas_precio_marca_2, indicador_subidas_precio_marca_2, indicador_iguales_precio_marca_2, cantidad_variacion_precio_marca_3, indicador_bajadas_precio_marca_3, indicador_subidas_precio_marca_3, indicador_iguales_precio_marca_3, cantidad_variacion_precio_marca_4, indicador_bajadas_precio_marca_4, indicador_subidas_precio_marca_4, indicador_iguales_precio_marca_4, cantidad_variacion_precio_marca_5, indicador_bajadas_precio_marca_5, indicador_subidas_precio_marca_5, indicador_iguales_precio_marca_5], axis=1)

In [106]:
df_variacion_precio.head(30)

,ID,Cantidad de Variación del Precio Marca 1,Indicador Bajas de Precio Marca 1,Indicador Subidas de Precio Marca 1,Indicador Sostenimiento de Precio Marca 1,Cantidad de Variación del Precio Marca 2,Indicador Bajas de Precio Marca 2,Indicador Subidas de Precio Marca 2,Indicador Sostenimiento de Precio Marca 2,Cantidad de Variación del Precio Marca 3,...,Indicador Subidas de Precio Marca 3,Indicador Sostenimiento de Precio Marca 3,Cantidad de Variación del Precio Marca 4,Indicador Bajas de Precio Marca 4,Indicador Subidas de Precio Marca 4,Indicador Sostenimiento de Precio Marca 4,Cantidad de Variación del Precio Marca 5,Indicador Bajas de Precio Marca 5,Indicador Subidas de Precio Marca 5,Indicador Sostenimiento de Precio Marca 5
0,200000001,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00,...,0.0,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.0,0.0
1,200000001,-0.08,1.0,0.0,0.0,0.02,0.0,1.0,0.0,-0.02,...,0.0,0.0,0.00,0.0,0.0,1.0,0.00,0.0,0.0,1.0
2,200000001,0.00,0.0,0.0,1.0,0.00,0.0,0.0,1.0,0.00,...,0.0,1.0,0.00,0.0,0.0,1.0,0.00,0.0,0.0,1.0
3,200000001,0.01,0.0,1.0,0.0,0.00,0.0,0.0,1.0,-0.01,...,0.0,0.0,0.00,0.0,0.0,1.0,0.00,0.0,0.0,1.0
4,200000001,0.00,0.0,0.0,1.0,0.00,0.0,0.0,1.0,0.01,...,1.0,0.0,0.00,0.0,0.0,1.0,0.00,0.0,0.0,1.0
5,200000001,-0.02,1.0,0.0,0.0,0.01,0.0,1.0,0.0,0.00,...,0.0,1.0,0.00,0.0,0.0,1.0,0.00,0.0,0.0,1.0
6,200000001,0.00,0.0,0.0,1.0,0.00,0.0,0.0,1.0,0.00,...,0.0,1.0,0.00,0.0,0.0,1.0,0.01,0.0,1.0,0.0
7,200000001,0.00,0.0,0.0,1.0,0.00,0.0,0.0,1.0,0.00,...,0.0,1.0,0.00,0.0,0.0,1.0,0.00,0.0,0.0,1.0
8,200000001,-0.15,1.0,0.0,0.0,-0.32,1.0,0.0,0.0,-0.02,...,0.0,0.0,0.00,0.0,0.0,1.0,0.00,0.0,0.0,1.0
9,200000001,0.00,0.0,0.0,1.0,0.00,0.0,0.0,1.0,0.00,...,0.0,1.0,0.00,0.0,0.0,1.0,0.00,0.0,0.0,1.0
10,200000001,0.00,0.0,0.0,1.0,0.29,0.0,1.0,0.0,-0.04,...,0.0,0.0,0.00,0.0,0.0,1.0,-0.08,1.0,0.0,0.0
11,200000001,0.04,0.0,1.0,0.0,0.03,0.0,1.0,0.0,-0.02,...,0.0,0.0,0.03,0.0,1.0,0.0,0.03,0.0,1.0,0.0
12,200000001,0.00,0.0,0.0,1.0,0.00,0.0,0.0,1.0,0.00,...,0.0,1.0,0.00,0.0,0.0,1.0,0.00,0.0,0.0,1.0
13,200000001,-0.03,1.0,0.0,0.0,-0.05,1.0,0.0,0.0,0.04,...,1.0,0.0,0.00,0.0,0.0,1.0,-0.12,1.0,0.0,0.0
14,200000001,0.11,0.0,1.0,0.0,0.00,0.0,0.0,1.0,0.00,...,0.0,1.0,0.00,0.0,0.0,1.0,0.00,0.0,0.0,1.0
15,200000001,0.00,0.0,0.0,1.0,0.05,0.0,1.0,0.0,0.04,...,1.0,0.0,0.00,0.0,0.0,1.0,-0.01,1.0,0.0,0.0
16,200000001,-0.08,1.0,0.0,0.0,-0.32,1.0,0.0,0.0,0.00,...,0.0,1.0,0.00,0.0,0.0,1.0,0.06,0.0,1.0,0.0
17,200000001,0.00,0.0,0.0,1.0,-0.12,1.0,0.0,0.0,0.00,...,0.0,1.0,0.00,0.0,0.0,1.0,-0.15,1.0,0.0,0.0
18,200000001,0.08,0.0,1.0,0.0,0.44,0.0,1.0,0.0,-0.04,...,0.0,0.0,0.00,0.0,0.0,1.0,0.27,0.0,1.0,0.0
19,200000001,0.00,0.0,0.0,1.0,0.00,0.0,0.0,1.0,0.04,...,1.0,0.0,-0.15,1.0,0.0,0.0,0.00,0.0,0.0,1.0
20,200000001,0.00,0.0,0.0,1.0,0.00,0.0,0.0,1.0,0.00,...,0.0,1.0,0.00,0.0,0.0,1.0,0.00,0.0,0.0,1.0
21,200000001,-0.04,1.0,0.0,0.0,-0.59,1.0,0.0,0.0,0.00,...,0.0,1.0,0.19,0.0,1.0,0.0,0.00,0.0,0.0,1.0
22,200000001,-0.04,1.0,0.0,0.0,0.53,0.0,1.0,0.0,-0.06,...,0.0,0.0,0.00,0.0,0.0,1.0,0.00,0.0,0.0,1.0
23,200000001,-0.20,1.0,0.0,0.0,0.05,0.0,1.0,0.0,0.06,...,1.0,0.0,0.00,0.0,0.0,1.0,0.00,0.0,0.0,1.0
24,200000001,0.02,0.0,1.0,0.0,-0.54,1.0,0.0,0.0,0.00,...,0.0,1.0,0.00,0.0,0.0,1.0,0.01,0.0,1.0,0.0
25,200000001,0.18,0.0,1.0,0.0,0.55,0.0,1.0,0.0,0.00,...,0.0,1.0,0.00,0.0,0.0,1.0,-0.04,1.0,0.0,0.0
26,200000001,0.00,0.0,0.0,1.0,0.00,0.0,0.0,1.0,-0.05,...,0.0,0.0,0.00,0.0,0.0,1.0,-0.02,1.0,0.0,0.0
27,200000001,0.00,0.0,0.0,1.0,0.00,0.0,0.0,1.0,0.00,...,0.0,1.0,0.00,0.0,0.0,1.0,0.00,0.0,0.0,1.0
28,200000001,0.00,0.0,0.0,1.0,0.00,0.0,0.0,1.0,0.00,...,0.0,1.0,0.00,0.0,0.0,1.0,0.01,0.0,1.0,0.0
29,200000001,0.07,0.0,1.0,0.0,-0.02,1.0,0.0,0.0,0.03,...,1.0,0.0,-0.27,1.0,0.0,0.0,-0.26,1.0,0.0,0.0

In [107]:
compras_sube_precio_M1 = np.empty(len(df))
compras_sube_precio_M2 = np.empty(len(df))
compras_sube_precio_M3 = np.empty(len(df))
compras_sube_precio_M4 = np.empty(len(df))
compras_sube_precio_M5 = np.empty(len(df))

compras_baja_precio_M1 = np.empty(len(df))
compras_baja_precio_M2 = np.empty(len(df))
compras_baja_precio_M3 = np.empty(len(df))
compras_baja_precio_M4 = np.empty(len(df))
compras_baja_precio_M5 = np.empty(len(df))

compras_igual_precio_M1 = np.empty(len(df))
compras_igual_precio_M2 = np.empty(len(df))
compras_igual_precio_M3 = np.empty(len(df))
compras_igual_precio_M4 = np.empty(len(df))
compras_igual_precio_M5 = np.empty(len(df))

variacion_precio_M1 = np.empty(len(df))
variacion_precio_M2 = np.empty(len(df))
variacion_precio_M3 = np.empty(len(df))
variacion_precio_M4 = np.empty(len(df))
variacion_precio_M5 = np.empty(len(df))

for i in range(len(df)):
    if (df.loc[i, 'MARCA'] == 0):
        compras_sube_precio_M1[i] = 0
        compras_sube_precio_M2[i] = 0
        compras_sube_precio_M3[i] = 0
        compras_sube_precio_M4[i] = 0
        compras_sube_precio_M5[i] = 0
        compras_baja_precio_M1[i] = 0
        compras_baja_precio_M2[i] = 0
        compras_baja_precio_M3[i] = 0
        compras_baja_precio_M4[i] = 0
        compras_baja_precio_M5[i] = 0
        compras_igual_precio_M1[i] = 0
        compras_igual_precio_M2[i] = 0
        compras_igual_precio_M3[i] = 0
        compras_igual_precio_M4[i] = 0
        compras_igual_precio_M5[i] = 0
        variacion_precio_M1[i] = 0
        variacion_precio_M2[i] = 0
        variacion_precio_M3[i] = 0
        variacion_precio_M4[i] = 0
        variacion_precio_M5[i] = 0
    elif (df.loc[i, 'MARCA'] == 1 and df_variacion_precio.loc[i, 'Indicador Bajas de Precio Marca 1'] == 1):
        compras_sube_precio_M1[i] = 0
        compras_sube_precio_M2[i] = 0
        compras_sube_precio_M3[i] = 0
        compras_sube_precio_M4[i] = 0
        compras_sube_precio_M5[i] = 0
        compras_baja_precio_M1[i] = 1
        compras_baja_precio_M2[i] = 0
        compras_baja_precio_M3[i] = 0
        compras_baja_precio_M4[i] = 0
        compras_baja_precio_M5[i] = 0
        compras_igual_precio_M1[i] = 0
        compras_igual_precio_M2[i] = 0
        compras_igual_precio_M3[i] = 0
        compras_igual_precio_M4[i] = 0
        compras_igual_precio_M5[i] = 0
        variacion_precio_M1[i] = df_variacion_precio.loc[i, 'Cantidad de Variación del Precio Marca 1']
        variacion_precio_M2[i] = 0
        variacion_precio_M3[i] = 0
        variacion_precio_M4[i] = 0
        variacion_precio_M5[i] = 0        
    elif (df.loc[i, 'MARCA'] == 1 and df_variacion_precio.loc[i, 'Indicador Subidas de Precio Marca 1'] == 1):
        compras_sube_precio_M1[i] = 1
        compras_sube_precio_M2[i] = 0
        compras_sube_precio_M3[i] = 0
        compras_sube_precio_M4[i] = 0
        compras_sube_precio_M5[i] = 0
        compras_baja_precio_M1[i] = 0
        compras_baja_precio_M2[i] = 0
        compras_baja_precio_M3[i] = 0
        compras_baja_precio_M4[i] = 0
        compras_baja_precio_M5[i] = 0
        compras_igual_precio_M1[i] = 0
        compras_igual_precio_M2[i] = 0
        compras_igual_precio_M3[i] = 0
        compras_igual_precio_M4[i] = 0
        compras_igual_precio_M5[i] = 0
        variacion_precio_M1[i] = df_variacion_precio.loc[i, 'Cantidad de Variación del Precio Marca 1']
        variacion_precio_M2[i] = 0
        variacion_precio_M3[i] = 0
        variacion_precio_M4[i] = 0
        variacion_precio_M5[i] = 0      
    elif (df.loc[i, 'MARCA'] == 1 and df_variacion_precio.loc[i, 'Indicador Sostenimiento de Precio Marca 1'] == 1):
        compras_sube_precio_M1[i] = 0
        compras_sube_precio_M2[i] = 0
        compras_sube_precio_M3[i] = 0
        compras_sube_precio_M4[i] = 0
        compras_sube_precio_M5[i] = 0
        compras_baja_precio_M1[i] = 0
        compras_baja_precio_M2[i] = 0
        compras_baja_precio_M3[i] = 0
        compras_baja_precio_M4[i] = 0
        compras_baja_precio_M5[i] = 0
        compras_igual_precio_M1[i] = 1
        compras_igual_precio_M2[i] = 0
        compras_igual_precio_M3[i] = 0
        compras_igual_precio_M4[i] = 0
        compras_igual_precio_M5[i] = 0
        variacion_precio_M1[i] = df_variacion_precio.loc[i, 'Cantidad de Variación del Precio Marca 1']
        variacion_precio_M2[i] = 0
        variacion_precio_M3[i] = 0
        variacion_precio_M4[i] = 0
        variacion_precio_M5[i] = 0        
    elif (df.loc[i, 'MARCA'] == 2 and df_variacion_precio.loc[i, 'Indicador Bajas de Precio Marca 2'] == 1):
        compras_sube_precio_M1[i] = 0
        compras_sube_precio_M2[i] = 0
        compras_sube_precio_M3[i] = 0
        compras_sube_precio_M4[i] = 0
        compras_sube_precio_M5[i] = 0
        compras_baja_precio_M1[i] = 0
        compras_baja_precio_M2[i] = 1
        compras_baja_precio_M3[i] = 0
        compras_baja_precio_M4[i] = 0
        compras_baja_precio_M5[i] = 0
        compras_igual_precio_M1[i] = 0
        compras_igual_precio_M2[i] = 0
        compras_igual_precio_M3[i] = 0
        compras_igual_precio_M4[i] = 0
        compras_igual_precio_M5[i] = 0
        variacion_precio_M1[i] = 0
        variacion_precio_M2[i] = df_variacion_precio.loc[i, 'Cantidad de Variación del Precio Marca 2']
        variacion_precio_M3[i] = 0
        variacion_precio_M4[i] = 0
        variacion_precio_M5[i] = 0        
    elif (df.loc[i, 'MARCA'] == 2 and df_variacion_precio.loc[i, 'Indicador Subidas de Precio Marca 2'] == 1):
        compras_sube_precio_M1[i] = 0
        compras_sube_precio_M2[i] = 1
        compras_sube_precio_M3[i] = 0
        compras_sube_precio_M4[i] = 0
        compras_sube_precio_M5[i] = 0
        compras_baja_precio_M1[i] = 0
        compras_baja_precio_M2[i] = 0
        compras_baja_precio_M3[i] = 0
        compras_baja_precio_M4[i] = 0
        compras_baja_precio_M5[i] = 0
        compras_igual_precio_M1[i] = 0
        compras_igual_precio_M2[i] = 0
        compras_igual_precio_M3[i] = 0
        compras_igual_precio_M4[i] = 0
        compras_igual_precio_M5[i] = 0
        variacion_precio_M1[i] = 0
        variacion_precio_M2[i] = df_variacion_precio.loc[i, 'Cantidad de Variación del Precio Marca 2']
        variacion_precio_M3[i] = 0
        variacion_precio_M4[i] = 0
        variacion_precio_M5[i] = 0      
    elif (df.loc[i, 'MARCA'] == 2 and df_variacion_precio.loc[i, 'Indicador Sostenimiento de Precio Marca 2'] == 1):
        compras_sube_precio_M1[i] = 0
        compras_sube_precio_M2[i] = 0
        compras_sube_precio_M3[i] = 0
        compras_sube_precio_M4[i] = 0
        compras_sube_precio_M5[i] = 0
        compras_baja_precio_M1[i] = 0
        compras_baja_precio_M2[i] = 0
        compras_baja_precio_M3[i] = 0
        compras_baja_precio_M4[i] = 0
        compras_baja_precio_M5[i] = 0
        compras_igual_precio_M1[i] = 0
        compras_igual_precio_M2[i] = 1
        compras_igual_precio_M3[i] = 0
        compras_igual_precio_M4[i] = 0
        compras_igual_precio_M5[i] = 0
        variacion_precio_M1[i] = 0
        variacion_precio_M2[i] = df_variacion_precio.loc[i, 'Cantidad de Variación del Precio Marca 2']
        variacion_precio_M3[i] = 0
        variacion_precio_M4[i] = 0
        variacion_precio_M5[i] = 0         
    elif (df.loc[i, 'MARCA'] == 3 and df_variacion_precio.loc[i, 'Indicador Bajas de Precio Marca 3'] == 1):
        compras_sube_precio_M1[i] = 0
        compras_sube_precio_M2[i] = 0
        compras_sube_precio_M3[i] = 0
        compras_sube_precio_M4[i] = 0
        compras_sube_precio_M5[i] = 0
        compras_baja_precio_M1[i] = 0
        compras_baja_precio_M2[i] = 0
        compras_baja_precio_M3[i] = 1
        compras_baja_precio_M4[i] = 0
        compras_baja_precio_M5[i] = 0
        compras_igual_precio_M1[i] = 0
        compras_igual_precio_M2[i] = 0
        compras_igual_precio_M3[i] = 0
        compras_igual_precio_M4[i] = 0
        compras_igual_precio_M5[i] = 0
        variacion_precio_M1[i] = 0
        variacion_precio_M2[i] = 0
        variacion_precio_M3[i] = df_variacion_precio.loc[i, 'Cantidad de Variación del Precio Marca 3']
        variacion_precio_M4[i] = 0
        variacion_precio_M5[i] = 0        
    elif (df.loc[i, 'MARCA'] == 3 and df_variacion_precio.loc[i, 'Indicador Subidas de Precio Marca 3'] == 1):
        compras_sube_precio_M1[i] = 0
        compras_sube_precio_M2[i] = 0
        compras_sube_precio_M3[i] = 1
        compras_sube_precio_M4[i] = 0
        compras_sube_precio_M5[i] = 0
        compras_baja_precio_M1[i] = 0
        compras_baja_precio_M2[i] = 0
        compras_baja_precio_M3[i] = 0
        compras_baja_precio_M4[i] = 0
        compras_baja_precio_M5[i] = 0
        compras_igual_precio_M1[i] = 0
        compras_igual_precio_M2[i] = 0
        compras_igual_precio_M3[i] = 0
        compras_igual_precio_M4[i] = 0
        compras_igual_precio_M5[i] = 0
        variacion_precio_M1[i] = 0
        variacion_precio_M2[i] = 0
        variacion_precio_M3[i] = df_variacion_precio.loc[i, 'Cantidad de Variación del Precio Marca 3']
        variacion_precio_M4[i] = 0
        variacion_precio_M5[i] = 0      
    elif (df.loc[i, 'MARCA'] == 3 and df_variacion_precio.loc[i, 'Indicador Sostenimiento de Precio Marca 3'] == 1):
        compras_sube_precio_M1[i] = 0
        compras_sube_precio_M2[i] = 0
        compras_sube_precio_M3[i] = 0
        compras_sube_precio_M4[i] = 0
        compras_sube_precio_M5[i] = 0
        compras_baja_precio_M1[i] = 0
        compras_baja_precio_M2[i] = 0
        compras_baja_precio_M3[i] = 0
        compras_baja_precio_M4[i] = 0
        compras_baja_precio_M5[i] = 0
        compras_igual_precio_M1[i] = 0
        compras_igual_precio_M2[i] = 0
        compras_igual_precio_M3[i] = 1
        compras_igual_precio_M4[i] = 0
        compras_igual_precio_M5[i] = 0
        variacion_precio_M1[i] = 0
        variacion_precio_M2[i] = 0
        variacion_precio_M3[i] = df_variacion_precio.loc[i, 'Cantidad de Variación del Precio Marca 3']
        variacion_precio_M4[i] = 0
        variacion_precio_M5[i] = 0         
    elif (df.loc[i, 'MARCA'] == 4 and df_variacion_precio.loc[i, 'Indicador Bajas de Precio Marca 4'] == 1):
        compras_sube_precio_M1[i] = 0
        compras_sube_precio_M2[i] = 0
        compras_sube_precio_M3[i] = 0
        compras_sube_precio_M4[i] = 0
        compras_sube_precio_M5[i] = 0
        compras_baja_precio_M1[i] = 0
        compras_baja_precio_M2[i] = 0
        compras_baja_precio_M3[i] = 0
        compras_baja_precio_M4[i] = 1
        compras_baja_precio_M5[i] = 0
        compras_igual_precio_M1[i] = 0
        compras_igual_precio_M2[i] = 0
        compras_igual_precio_M3[i] = 0
        compras_igual_precio_M4[i] = 0
        compras_igual_precio_M5[i] = 0
        variacion_precio_M1[i] = 0
        variacion_precio_M2[i] = 0
        variacion_precio_M3[i] = 0
        variacion_precio_M4[i] = df_variacion_precio.loc[i, 'Cantidad de Variación del Precio Marca 4']
        variacion_precio_M5[i] = 0        
    elif (df.loc[i, 'MARCA'] == 4 and df_variacion_precio.loc[i, 'Indicador Subidas de Precio Marca 4'] == 1):
        compras_sube_precio_M1[i] = 0
        compras_sube_precio_M2[i] = 0
        compras_sube_precio_M3[i] = 0
        compras_sube_precio_M4[i] = 1
        compras_sube_precio_M5[i] = 0
        compras_baja_precio_M1[i] = 0
        compras_baja_precio_M2[i] = 0
        compras_baja_precio_M3[i] = 0
        compras_baja_precio_M4[i] = 0
        compras_baja_precio_M5[i] = 0
        compras_igual_precio_M1[i] = 0
        compras_igual_precio_M2[i] = 0
        compras_igual_precio_M3[i] = 0
        compras_igual_precio_M4[i] = 0
        compras_igual_precio_M5[i] = 0
        variacion_precio_M1[i] = 0
        variacion_precio_M2[i] = 0
        variacion_precio_M3[i] = 0
        variacion_precio_M4[i] = df_variacion_precio.loc[i, 'Cantidad de Variación del Precio Marca 4']
        variacion_precio_M5[i] = 0      
    elif (df.loc[i, 'MARCA'] == 4 and df_variacion_precio.loc[i, 'Indicador Sostenimiento de Precio Marca 4'] == 1):
        compras_sube_precio_M1[i] = 0
        compras_sube_precio_M2[i] = 0
        compras_sube_precio_M3[i] = 0
        compras_sube_precio_M4[i] = 0
        compras_sube_precio_M5[i] = 0
        compras_baja_precio_M1[i] = 0
        compras_baja_precio_M2[i] = 0
        compras_baja_precio_M3[i] = 0
        compras_baja_precio_M4[i] = 0
        compras_baja_precio_M5[i] = 0
        compras_igual_precio_M1[i] = 0
        compras_igual_precio_M2[i] = 0
        compras_igual_precio_M3[i] = 0
        compras_igual_precio_M4[i] = 1
        compras_igual_precio_M5[i] = 0
        variacion_precio_M1[i] = 0
        variacion_precio_M2[i] = 0
        variacion_precio_M3[i] = 0
        variacion_precio_M4[i] = df_variacion_precio.loc[i, 'Cantidad de Variación del Precio Marca 4']
        variacion_precio_M5[i] = 0
    elif (df.loc[i, 'MARCA'] == 5 and df_variacion_precio.loc[i, 'Indicador Bajas de Precio Marca 5'] == 1):
        compras_sube_precio_M1[i] = 0
        compras_sube_precio_M2[i] = 0
        compras_sube_precio_M3[i] = 0
        compras_sube_precio_M4[i] = 0
        compras_sube_precio_M5[i] = 0
        compras_baja_precio_M1[i] = 0
        compras_baja_precio_M2[i] = 0
        compras_baja_precio_M3[i] = 0
        compras_baja_precio_M4[i] = 0
        compras_baja_precio_M5[i] = 1
        compras_igual_precio_M1[i] = 0
        compras_igual_precio_M2[i] = 0
        compras_igual_precio_M3[i] = 0
        compras_igual_precio_M4[i] = 0
        compras_igual_precio_M5[i] = 0
        variacion_precio_M1[i] = 0
        variacion_precio_M2[i] = 0
        variacion_precio_M3[i] = 0
        variacion_precio_M4[i] = 0
        variacion_precio_M5[i] = df_variacion_precio.loc[i, 'Cantidad de Variación del Precio Marca 5']
    elif (df.loc[i, 'MARCA'] == 5 and df_variacion_precio.loc[i, 'Indicador Subidas de Precio Marca 5'] == 1):
        compras_sube_precio_M1[i] = 0
        compras_sube_precio_M2[i] = 0
        compras_sube_precio_M3[i] = 0
        compras_sube_precio_M4[i] = 0
        compras_sube_precio_M5[i] = 1
        compras_baja_precio_M1[i] = 0
        compras_baja_precio_M2[i] = 0
        compras_baja_precio_M3[i] = 0
        compras_baja_precio_M4[i] = 0
        compras_baja_precio_M5[i] = 0
        compras_igual_precio_M1[i] = 0
        compras_igual_precio_M2[i] = 0
        compras_igual_precio_M3[i] = 0
        compras_igual_precio_M4[i] = 0
        compras_igual_precio_M5[i] = 0
        variacion_precio_M1[i] = 0
        variacion_precio_M2[i] = 0
        variacion_precio_M3[i] = 0
        variacion_precio_M4[i] = 0
        variacion_precio_M5[i] = df_variacion_precio.loc[i, 'Cantidad de Variación del Precio Marca 5']      
    elif (df.loc[i, 'MARCA'] == 5 and df_variacion_precio.loc[i, 'Indicador Sostenimiento de Precio Marca 5'] == 1):
        compras_sube_precio_M1[i] = 0
        compras_sube_precio_M2[i] = 0
        compras_sube_precio_M3[i] = 0
        compras_sube_precio_M4[i] = 0
        compras_sube_precio_M5[i] = 0
        compras_baja_precio_M1[i] = 0
        compras_baja_precio_M2[i] = 0
        compras_baja_precio_M3[i] = 0
        compras_baja_precio_M4[i] = 0
        compras_baja_precio_M5[i] = 0
        compras_igual_precio_M1[i] = 0
        compras_igual_precio_M2[i] = 0
        compras_igual_precio_M3[i] = 0
        compras_igual_precio_M4[i] = 0
        compras_igual_precio_M5[i] = 1
        variacion_precio_M1[i] = 0
        variacion_precio_M2[i] = 0
        variacion_precio_M3[i] = 0
        variacion_precio_M4[i] = 0
        variacion_precio_M5[i] = df_variacion_precio.loc[i, 'Cantidad de Variación del Precio Marca 5']
        
compras_sube_precio_M1 = pd.DataFrame(compras_sube_precio_M1)
compras_sube_precio_M2 = pd.DataFrame(compras_sube_precio_M2)
compras_sube_precio_M3 = pd.DataFrame(compras_sube_precio_M3)
compras_sube_precio_M4 = pd.DataFrame(compras_sube_precio_M4)
compras_sube_precio_M5 = pd.DataFrame(compras_sube_precio_M5)
compras_baja_precio_M1 = pd.DataFrame(compras_baja_precio_M1)
compras_baja_precio_M2 = pd.DataFrame(compras_baja_precio_M2)
compras_baja_precio_M3 = pd.DataFrame(compras_baja_precio_M3)
compras_baja_precio_M4 = pd.DataFrame(compras_baja_precio_M4)
compras_baja_precio_M5 = pd.DataFrame(compras_baja_precio_M5)
compras_igual_precio_M1 = pd.DataFrame(compras_igual_precio_M1)
compras_igual_precio_M2 = pd.DataFrame(compras_igual_precio_M2)
compras_igual_precio_M3 = pd.DataFrame(compras_igual_precio_M3)
compras_igual_precio_M4 = pd.DataFrame(compras_igual_precio_M4)
compras_igual_precio_M5 = pd.DataFrame(compras_igual_precio_M5)
variacion_precio_M1 = pd.DataFrame(variacion_precio_M1)
variacion_precio_M2 = pd.DataFrame(variacion_precio_M2)
variacion_precio_M3 = pd.DataFrame(variacion_precio_M3)
variacion_precio_M4 = pd.DataFrame(variacion_precio_M4)
variacion_precio_M5 = pd.DataFrame(variacion_precio_M5)     

header_compras_sube_precio_M1 = ['Compras al subir el precio Marca 1']
header_compras_sube_precio_M2 = ['Compras al subir el precio Marca 2']
header_compras_sube_precio_M3 = ['Compras al subir el precio Marca 3']
header_compras_sube_precio_M4 = ['Compras al subir el precio Marca 4']
header_compras_sube_precio_M5 = ['Compras al subir el precio Marca 5']
header_compras_baja_precio_M1 = ['Compras al bajar el precio Marca 1']
header_compras_baja_precio_M2 = ['Compras al bajar el precio Marca 2']
header_compras_baja_precio_M3 = ['Compras al bajar el precio Marca 3']
header_compras_baja_precio_M4 = ['Compras al bajar el precio Marca 4']
header_compras_baja_precio_M5 = ['Compras al bajar el precio Marca 5']
header_compras_igual_precio_M1 = ['Compras siendo igual el precio Marca 1']
header_compras_igual_precio_M2 = ['Compras siendo igual el precio Marca 2']
header_compras_igual_precio_M3 = ['Compras siendo igual el precio Marca 3']
header_compras_igual_precio_M4 = ['Compras siendo igual el precio Marca 4']
header_compras_igual_precio_M5 = ['Compras siendo igual el precio Marca 5']
header_variacion_precio_M1 = ['Variacion del Precio en Compra Marca 1']
header_variacion_precio_M2 = ['Variacion del Precio en Compra Marca 2']
header_variacion_precio_M3 = ['Variacion del Precio en Compra Marca 3']
header_variacion_precio_M4 = ['Variacion del Precio en Compra Marca 4']
header_variacion_precio_M5 = ['Variacion del Precio en Compra Marca 5'] 
        
compras_sube_precio_M1.columns = header_compras_sube_precio_M1
compras_sube_precio_M2.columns = header_compras_sube_precio_M2
compras_sube_precio_M3.columns = header_compras_sube_precio_M3
compras_sube_precio_M4.columns = header_compras_sube_precio_M4
compras_sube_precio_M5.columns = header_compras_sube_precio_M5
compras_baja_precio_M1.columns = header_compras_baja_precio_M1
compras_baja_precio_M2.columns = header_compras_baja_precio_M2
compras_baja_precio_M3.columns = header_compras_baja_precio_M3
compras_baja_precio_M4.columns = header_compras_baja_precio_M4
compras_baja_precio_M5.columns = header_compras_baja_precio_M5
compras_igual_precio_M1.columns = header_compras_igual_precio_M1
compras_igual_precio_M2.columns = header_compras_igual_precio_M2
compras_igual_precio_M3.columns = header_compras_igual_precio_M3
compras_igual_precio_M4.columns = header_compras_igual_precio_M4
compras_igual_precio_M5.columns = header_compras_igual_precio_M5
variacion_precio_M1.columns = header_variacion_precio_M1 
variacion_precio_M2.columns = header_variacion_precio_M2
variacion_precio_M3.columns = header_variacion_precio_M3 
variacion_precio_M4.columns = header_variacion_precio_M4 
variacion_precio_M5.columns = header_variacion_precio_M5  

df_variacion_precio = pd.concat([df['ID'], variacion_precio_M1, compras_baja_precio_M1, compras_igual_precio_M1, compras_sube_precio_M1, variacion_precio_M2, compras_baja_precio_M2, compras_igual_precio_M2, compras_sube_precio_M2, variacion_precio_M3, compras_baja_precio_M3, compras_igual_precio_M3, compras_sube_precio_M3, variacion_precio_M4, compras_baja_precio_M4, compras_igual_precio_M4, compras_sube_precio_M4, variacion_precio_M5, compras_baja_precio_M5, compras_igual_precio_M5, compras_sube_precio_M5], axis=1)

In [108]:
df_variacion_precio.head(30)

,ID,Variacion del Precio en Compra Marca 1,Compras al bajar el precio Marca 1,Compras siendo igual el precio Marca 1,Compras al subir el precio Marca 1,Variacion del Precio en Compra Marca 2,Compras al bajar el precio Marca 2,Compras siendo igual el precio Marca 2,Compras al subir el precio Marca 2,Variacion del Precio en Compra Marca 3,...,Compras siendo igual el precio Marca 3,Compras al subir el precio Marca 3,Variacion del Precio en Compra Marca 4,Compras al bajar el precio Marca 4,Compras siendo igual el precio Marca 4,Compras al subir el precio Marca 4,Variacion del Precio en Compra Marca 5,Compras al bajar el precio Marca 5,Compras siendo igual el precio Marca 5,Compras al subir el precio Marca 5
0,200000001,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0
1,200000001,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0
2,200000001,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0
3,200000001,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0
4,200000001,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0
5,200000001,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0
6,200000001,0.0,0.0,0.0,0.0,0.00,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0
7,200000001,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0
8,200000001,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0
9,200000001,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0
10,200000001,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0
11,200000001,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.03,0.0,0.0,1.0
12,200000001,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0
13,200000001,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0
14,200000001,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0
15,200000001,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0
16,200000001,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0
17,200000001,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0
18,200000001,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0
19,200000001,0.0,0.0,1.0,0.0,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0
20,200000001,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0
21,200000001,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0
22,200000001,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0
23,200000001,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0
24,200000001,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.00,0.0,0.0,0.0
25,200000001,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0
26,200000001,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0
27,200000001,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0
28,200000001,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0
29,200000001,0.0,0.0,0.0,0.0,-0.02,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0

In [109]:
df_variacion_precio_indicadores = df_variacion_precio[['ID',  'Compras al bajar el precio Marca 1', 'Compras siendo igual el precio Marca 1', 'Compras al subir el precio Marca 1', 'Compras al bajar el precio Marca 2', 'Compras siendo igual el precio Marca 2', 'Compras al subir el precio Marca 2', 'Compras al bajar el precio Marca 3', 'Compras siendo igual el precio Marca 3', 'Compras al subir el precio Marca 3', 'Compras al bajar el precio Marca 4', 'Compras siendo igual el precio Marca 4', 'Compras al subir el precio Marca 4', 'Compras al bajar el precio Marca 5', 'Compras siendo igual el precio Marca 5', 'Compras al subir el precio Marca 5']]
df_variacion_precio_cantidades = df_variacion_precio[['ID', 'Variacion del Precio en Compra Marca 1', 'Variacion del Precio en Compra Marca 2', 'Variacion del Precio en Compra Marca 3', 'Variacion del Precio en Compra Marca 4', 'Variacion del Precio en Compra Marca 5']]
df_variacion_precio_indicadores

,ID,Compras al bajar el precio Marca 1,Compras siendo igual el precio Marca 1,Compras al subir el precio Marca 1,Compras al bajar el precio Marca 2,Compras siendo igual el precio Marca 2,Compras al subir el precio Marca 2,Compras al bajar el precio Marca 3,Compras siendo igual el precio Marca 3,Compras al subir el precio Marca 3,Compras al bajar el precio Marca 4,Compras siendo igual el precio Marca 4,Compras al subir el precio Marca 4,Compras al bajar el precio Marca 5,Compras siendo igual el precio Marca 5,Compras al subir el precio Marca 5
0,200000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,200000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,200000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,200000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,200000001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58688,200000500,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
58689,200000500,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
58690,200000500,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
58691,200000500,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
58692,200000500,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [110]:
df_variacion_precio_indicadores = df_variacion_precio_indicadores.groupby(['ID'],as_index=False).sum()
df_variacion_precio_indicadores
#df_variacion_precio_indicadores = df_variacion_precio_indicadores.drop(['ID'], axis=1)

,ID,Compras al bajar el precio Marca 1,Compras siendo igual el precio Marca 1,Compras al subir el precio Marca 1,Compras al bajar el precio Marca 2,Compras siendo igual el precio Marca 2,Compras al subir el precio Marca 2,Compras al bajar el precio Marca 3,Compras siendo igual el precio Marca 3,Compras al subir el precio Marca 3,Compras al bajar el precio Marca 4,Compras siendo igual el precio Marca 4,Compras al subir el precio Marca 4,Compras al bajar el precio Marca 5,Compras siendo igual el precio Marca 5,Compras al subir el precio Marca 5
0,200000001,0.0,1.0,0.0,2.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,2.0
1,200000002,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3.0,5.0,2.0,0.0,0.0,0.0
2,200000003,0.0,0.0,0.0,3.0,2.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0
3,200000004,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,4.0,4.0
4,200000005,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,5.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,200000496,0.0,0.0,1.0,4.0,9.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,2.0
496,200000497,0.0,1.0,0.0,9.0,14.0,5.0,0.0,0.0,0.0,2.0,11.0,0.0,0.0,1.0,0.0
497,200000498,3.0,1.0,1.0,6.0,12.0,5.0,2.0,6.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0
498,200000499,1.0,0.0,1.0,15.0,7.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,3.0
499,200000500,1.0,1.0,0.0,5.0,6.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [111]:
df_variacion_precio_cantidades

,ID,Variacion del Precio en Compra Marca 1,Variacion del Precio en Compra Marca 2,Variacion del Precio en Compra Marca 3,Variacion del Precio en Compra Marca 4,Variacion del Precio en Compra Marca 5
0,200000001,0.0,0.00,0.0,0.0,0.0
1,200000001,0.0,0.00,0.0,0.0,0.0
2,200000001,0.0,0.00,0.0,0.0,0.0
3,200000001,0.0,0.00,0.0,0.0,0.0
4,200000001,0.0,0.00,0.0,0.0,0.0
...,...,...,...,...,...,...
58688,200000500,0.0,0.00,0.0,0.0,0.0
58689,200000500,0.0,0.00,0.0,0.0,0.0
58690,200000500,0.0,0.00,0.0,0.0,0.0
58691,200000500,0.0,0.02,0.0,0.0,0.0
58692,200000500,0.0,0.00,0.0,0.0,0.0

In [112]:
df_variacion_precio_cantidades = df_variacion_precio_cantidades.groupby(['ID'],as_index=False).mean()
df_variacion_precio_cantidades

,ID,Variacion del Precio en Compra Marca 1,Variacion del Precio en Compra Marca 2,Variacion del Precio en Compra Marca 3,Variacion del Precio en Compra Marca 4,Variacion del Precio en Compra Marca 5
0,200000001,0.000000,-0.000693,0.000000,-0.003069,0.000396
1,200000002,0.000000,-0.003563,0.000000,-0.002989,0.000000
2,200000003,0.000000,-0.002990,0.000000,0.000000,-0.001753
3,200000004,0.000000,-0.003765,0.000000,0.000000,-0.000824
4,200000005,0.000000,0.000000,0.000000,0.000000,-0.001532
...,...,...,...,...,...,...
495,200000496,0.001000,-0.012083,0.000000,0.000000,0.000417
496,200000497,0.000000,-0.014500,0.000000,-0.002250,0.000000
497,200000498,-0.003053,-0.003588,-0.000229,0.000000,0.000000
498,200000499,-0.001226,-0.036509,0.000000,0.000000,0.001604
499,200000500,-0.001048,-0.012903,0.000000,0.000000,0.000000

In [113]:
df_variacion_precio_indicadores = df_variacion_precio_indicadores.drop(['ID'], axis=1)
df_variacion_precio_cantidades = df_variacion_precio_cantidades.drop(['ID'], axis=1)
df_final = pd.concat([df_final, df_variacion_precio_indicadores, df_variacion_precio_cantidades], axis=1)

In [114]:
df_final.head(20)

,ID,SEXO,ESTADO_CIVIL,EDAD,EDUCACION,INGRESO,OCUPACION,TAMAÑO_CIUDAD,Cantidad de Visitas,Dias sin Visita,...,Compras siendo igual el precio Marca 4,Compras al subir el precio Marca 4,Compras al bajar el precio Marca 5,Compras siendo igual el precio Marca 5,Compras al subir el precio Marca 5,Variacion del Precio en Compra Marca 1,Variacion del Precio en Compra Marca 2,Variacion del Precio en Compra Marca 3,Variacion del Precio en Compra Marca 4,Variacion del Precio en Compra Marca 5
0,200000001,0.0,0.0,47.0,1.0,110866.0,1.0,0.0,101,4,...,1.0,0.0,0.0,0.0,2.0,0.000000,-0.000693,0.000000,-0.003069,0.000396
1,200000002,1.0,1.0,52.0,2.0,159052.0,2.0,1.0,87,2,...,5.0,2.0,0.0,0.0,0.0,0.000000,-0.003563,0.000000,-0.002989,0.000000
2,200000003,0.0,0.0,28.0,0.0,113212.0,1.0,0.0,97,7,...,0.0,0.0,2.0,0.0,0.0,0.000000,-0.002990,0.000000,0.000000,-0.001753
3,200000004,0.0,0.0,37.0,1.0,119602.0,0.0,0.0,85,6,...,0.0,0.0,2.0,4.0,4.0,0.000000,-0.003765,0.000000,0.000000,-0.000824
4,200000005,0.0,0.0,49.0,1.0,121466.0,1.0,2.0,111,2,...,0.0,0.0,5.0,5.0,3.0,0.000000,0.000000,0.000000,0.000000,-0.001532
5,200000006,0.0,0.0,39.0,1.0,112347.0,1.0,2.0,86,4,...,0.0,0.0,3.0,4.0,1.0,0.000698,-0.003605,0.000000,0.000000,-0.006279
6,200000007,0.0,0.0,27.0,0.0,125190.0,2.0,1.0,83,10,...,1.0,0.0,2.0,0.0,1.0,0.000241,-0.009518,0.000843,0.000000,-0.000482
7,200000008,0.0,0.0,26.0,0.0,131122.0,1.0,0.0,97,2,...,0.0,0.0,2.0,0.0,1.0,0.000000,-0.012577,0.000000,0.000000,-0.000619
8,200000009,0.0,0.0,25.0,0.0,108960.0,0.0,0.0,102,8,...,0.0,0.0,0.0,0.0,0.0,0.000000,-0.006961,0.000000,0.000000,0.000000
9,200000010,0.0,0.0,32.0,0.0,69370.0,0.0,0.0,98,1,...,0.0,0.0,0.0,0.0,0.0,-0.002041,0.000204,0.000000,0.000000,0.000000
10,200000011,0.0,0.0,44.0,1.0,181262.0,2.0,2.0,104,5,...,0.0,0.0,7.0,10.0,7.0,0.000000,0.000000,0.000000,-0.001442,-0.008654
11,200000012,0.0,0.0,50.0,1.0,122830.0,1.0,1.0,105,4,...,0.0,0.0,4.0,3.0,5.0,-0.002286,0.000000,0.000000,0.000000,0.002381
12,200000013,0.0,0.0,34.0,1.0,116525.0,0.0,0.0,103,6,...,0.0,0.0,0.0,2.0,0.0,-0.001262,0.000097,0.000000,0.000000,0.000000
13,200000014,0.0,0.0,40.0,1.0,76881.0,0.0,0.0,111,12,...,1.0,0.0,1.0,1.0,0.0,0.000000,-0.005946,0.000000,0.000000,-0.000270
14,200000015,1.0,0.0,25.0,0.0,72188.0,0.0,0.0,115,1,...,0.0,0.0,0.0,0.0,0.0,-0.000696,-0.010087,0.000000,0.000000,0.000000
15,200000016,1.0,0.0,47.0,1.0,110287.0,1.0,0.0,106,4,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.008208,0.000000,0.000000,0.000000
16,200000017,0.0,0.0,29.0,0.0,102723.0,1.0,0.0,99,4,...,0.0,0.0,3.0,0.0,2.0,0.000000,-0.008586,0.000000,0.000000,-0.001313
17,200000018,0.0,0.0,25.0,0.0,104505.0,0.0,0.0,102,4,...,0.0,0.0,1.0,0.0,0.0,0.000000,0.003824,0.000000,0.000000,-0.000490
18,200000019,0.0,1.0,26.0,1.0,72429.0,0.0,0.0,167,6,...,0.0,0.0,1.0,1.0,1.0,-0.000539,-0.004910,0.000000,0.000000,0.001916
19,200000020,1.0,0.0,30.0,1.0,58207.0,0.0,0.0,101,6,...,1.0,0.0,0.0,0.0,0.0,0.001485,-0.005446,0.000000,0.000000,0.000000

In [115]:
df_final['Compras al Bajar Precio'] = df_final['Compras al bajar el precio Marca 1'] + df_final['Compras al bajar el precio Marca 2'] + df_final['Compras al bajar el precio Marca 3'] + df_final['Compras al bajar el precio Marca 4'] + df_final['Compras al bajar el precio Marca 5']
df_final['Compras al Subir Precio'] = df_final['Compras al subir el precio Marca 1'] + df_final['Compras al subir el precio Marca 2'] + df_final['Compras al subir el precio Marca 3'] + df_final['Compras al subir el precio Marca 4'] + df_final['Compras al subir el precio Marca 5']
df_final['Compras siendo Igual el Precio'] = df_final['Compras siendo igual el precio Marca 1'] + df_final['Compras siendo igual el precio Marca 2'] + df_final['Compras siendo igual el precio Marca 3'] + df_final['Compras siendo igual el precio Marca 4'] + df_final['Compras siendo igual el precio Marca 5']
df_final

,ID,SEXO,ESTADO_CIVIL,EDAD,EDUCACION,INGRESO,OCUPACION,TAMAÑO_CIUDAD,Cantidad de Visitas,Dias sin Visita,...,Compras siendo igual el precio Marca 5,Compras al subir el precio Marca 5,Variacion del Precio en Compra Marca 1,Variacion del Precio en Compra Marca 2,Variacion del Precio en Compra Marca 3,Variacion del Precio en Compra Marca 4,Variacion del Precio en Compra Marca 5,Compras al Bajar Precio,Compras al Subir Precio,Compras siendo Igual el Precio
0,200000001,0.0,0.0,47.0,1.0,110866.0,1.0,0.0,101,4,...,0.0,2.0,0.000000,-0.000693,0.000000,-0.003069,0.000396,3.0,3.0,3.0
1,200000002,1.0,1.0,52.0,2.0,159052.0,2.0,1.0,87,2,...,0.0,0.0,0.000000,-0.003563,0.000000,-0.002989,0.000000,4.0,2.0,5.0
2,200000003,0.0,0.0,28.0,0.0,113212.0,1.0,0.0,97,7,...,0.0,0.0,0.000000,-0.002990,0.000000,0.000000,-0.001753,5.0,3.0,2.0
3,200000004,0.0,0.0,37.0,1.0,119602.0,0.0,0.0,85,6,...,4.0,4.0,0.000000,-0.003765,0.000000,0.000000,-0.000824,3.0,4.0,4.0
4,200000005,0.0,0.0,49.0,1.0,121466.0,1.0,2.0,111,2,...,5.0,3.0,0.000000,0.000000,0.000000,0.000000,-0.001532,5.0,3.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,200000496,1.0,1.0,26.0,1.0,71021.0,0.0,0.0,120,8,...,1.0,2.0,0.001000,-0.012083,0.000000,0.000000,0.000417,5.0,4.0,11.0
496,200000497,0.0,0.0,60.0,2.0,89374.0,0.0,0.0,120,9,...,1.0,0.0,0.000000,-0.014500,0.000000,-0.002250,0.000000,11.0,5.0,27.0
497,200000498,1.0,1.0,29.0,1.0,114784.0,1.0,0.0,131,2,...,0.0,0.0,-0.003053,-0.003588,-0.000229,0.000000,0.000000,11.0,9.0,19.0
498,200000499,1.0,0.0,35.0,1.0,73266.0,0.0,0.0,106,4,...,0.0,3.0,-0.001226,-0.036509,0.000000,0.000000,0.001604,17.0,6.0,8.0
499,200000500,0.0,0.0,42.0,1.0,120946.0,1.0,0.0,124,5,...,0.0,0.0,-0.001048,-0.012903,0.000000,0.000000,0.000000,6.0,2.0,7.0

In [116]:
df_final.shape

(500, 82)

In [117]:
df_final.to_excel("DataframeFinal.xlsx", index=False)